.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-FETCHINVOICE" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-fetchinvoice -- Command for fetch an invoice for an offer
.SH
SYNOPSIS
.LP
\fB(WARNING: experimental-offers only)\fR
.PP
\fBfetchinvoice\fR \fIoffer\fR [\fIamount_msat\fR] [\fIquantity\fR] [\fIrecurrence_counter\fR] [\fIrecurrence_start\fR] [\fIrecurrence_label\fR] [\fItimeout\fR] [\fIpayer_note\fR] 
.SH
DESCRIPTION
.LP
The \fBfetchinvoice\fR RPC command contacts the issuer of an \fIoffer\fR to get an actual invoice that can be paid. It highlights any changes between the offer and the returned invoice.
.PP
If \fBfetchinvoice-noconnect\fR is not specified in the configuation, it will connect to the destination in the (currently common!) case where it cannot find a route which supports \fCoption_onion_messages\fR.
.IP "\(bu" 2
\fBoffer\fR (string): Offer string to get an actual invoice that can be paid.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): Required if the offer does not specify an amount at all, otherwise it is optional (but presumably if you set it to less than the offer, you will get an error from the issuer).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBquantity\fR (u64, optional): Required if the offer specifies quantity_max, otherwise it is not allowed.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBrecurrence_counter\fR (u64, optional): Required if the offer specifies recurrence, otherwise it is not allowed. recurrence_counter should first be set to 0, and incremented for each successive invoice in a given series.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBrecurrence_start\fR (number, optional): Required if the offer specifies recurrence_base with start_any_period set, otherwise it is not allowed. It indicates what period number to start at.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBrecurrence_label\fR (string, optional): Required if recurrence_counter is set, and otherwise is not allowed. It must be the same as prior fetchinvoice calls for the same recurrence, as it is used to link them together.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtimeout\fR (number, optional): If we don't get a reply before this we fail (default, 60 seconds).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayer_note\fR (string, optional): To ask the issuer to include in the fetched invoice.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBinvoice\fR (string): The BOLT12 invoice we fetched.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBchanges\fR (object): Summary of changes from offer.:
.RS
.IP "\(bu" 2
\fBdescription_appended\fR (string, optional): Extra characters appended to the \fIdescription\fR field.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdescription\fR (string, optional): A completely replaced \fIdescription\fR field.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBvendor_removed\fR (string, optional): The \fIvendor\fR from the offer, which is missing in the invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBvendor\fR (string, optional): A completely replaced \fIvendor\fR field.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): The amount, if different from the offer amount multiplied by any \fIquantity\fR (or the offer had no amount, or was not in BTC).
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBnext_period\fR (object, optional): Only for recurring invoices if the next period is under the \fIrecurrence_limit\fR.:
.RS
.IP "\(bu" 2
\fBcounter\fR (u64): The index of the next period to fetchinvoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstarttime\fR (u64): UNIX timestamp that the next period starts.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBendtime\fR (u64): UNIX timestamp that the next period ends.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpaywindow_start\fR (u64): UNIX timestamp of the earliest time that the next invoice can be fetched.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpaywindow_end\fR (u64): UNIX timestamp of the latest time that the next invoice can be fetched.
.RE
.SH
ERRORS
.LP
The following error codes may occur:
.IP "\(bu" 2
-1: Catchall nonspecific error.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1002: Offer has expired.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1003: Cannot find a route to the node making the offer.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1004: The node making the offer returned an error message.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1005: We timed out trying to fetch an invoice.
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-sendinvoice(7), lightning-pay(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli fetchinvoice -k \(dqoffer\(dq=\(dqlno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqgn3qzs2ge5hx6pqwdskcefpzcssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e\(dq \(dqpayer_note\(dq=\(dqThanks for the fish!\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:fetchinvoice#1\(dq,
  \(dqmethod\(dq: \(dqfetchinvoice\(dq,
  \(dqparams\(dq: {
    \(dqoffer\(dq: \(dqlno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqgn3qzs2ge5hx6pqwdskcefpzcssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e\(dq,
    \(dqpayer_note\(dq: \(dqThanks for the fish!\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqinvoice\(dq: \(dqlni1qqg9g04gczk9ntk4gsjg3aptwykk2q3qqc3xu3s3rg94nj40zfsy866mhu5vxne6tcej5878k2mneuvgjy8ssq38zq9q53nfwd5zqumpd3jjz93pqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4j5pqqc3xu3s3rg94nj40zfsy866mhu5vxne6tcej5878k2mneuvgjy84sggztuesttnr6atmya7afycpsvcg0wnzprn58n54lfhf2ragp0jq0e04j9z5dpsku6mnypnx7u3qw35x2grxd9eksgdqnqpz6g3kyz34nfrl7lm6c3rushzxey3a55ecjgs6qp2vz8q78j336kgr6euj6p39a209zw5kpkftk7h9te69vlmjg0arceagpaajague0zsszqk96htpgqn2wsznaas0zfdtf8v97ryz29jrn7rwgs5687ghgq5jusqr99dtx4jdj9nqpep5zxmynegrg6e7rm2l53ur8043h2yqzldyl5vh08h8ssaeq5jrvw9y24kztlwvc4nwagsuqqqqqqqqqqqqqqq9qqqqqqqqqqqqq8fykt06c5sqqqqqpfqyv65yfedgyqrp2s7qpxpjse8q8796qcrr5xwgfkqjue3urd6rs2rt2f68tk0vl2szyugtqggz953rvg9rtxj8lalh43z8epwydjfrmffn3y3p5qz5cywpu09rr4vlqsy2n7vmpn67ltzrj70znp70sk4m530j5vceq6jhk97h7ttzn09sh8m9gecarrt27v2tux8z6rr06sj9h60r05p4vhkhzsp0xf9ea4jgg\(dq,
  \(dqchanges\(dq: {}
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli fetchinvoice -k \(dqoffer\(dq=\(dqlno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqv85ysq2qepk7enxv4j3gqg2zcssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e\(dq \(dqamount_msat\(dq=2000000 \(dqquantity\(dq=2
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:fetchinvoice#2\(dq,
  \(dqmethod\(dq: \(dqfetchinvoice\(dq,
  \(dqparams\(dq: {
    \(dqoffer\(dq: \(dqlno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrcgqv85ysq2qepk7enxv4j3gqg2zcssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e\(dq,
    \(dqamount_msat\(dq: 2000000,
    \(dqquantity\(dq: 2
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqinvoice\(dq: \(dqlni1qqg86u6jfl660zfuk22sexem37r7xq3qqc3xu3s3rg94nj40zfsy866mhu5vxne6tcej5878k2mneuvgjy8ssqc0gfqq5pjrdanxvet9zsqs593pqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4j5pqqc3xu3s3rg94nj40zfsy866mhu5vxne6tcej5878k2mneuvgjy84yqc7sjq9vqgztqssxq2dwgnpqyhz3j68zx5cts28t6aqfgq937wsgvsmfncau3uhz8t05zvqytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82eq2rdjuqaychg3jndvsjrlu6y08aeuh4ytw6f6ak5n24p5n8zmsz2sqgrg3rg89hqfh6n7dfr0fugvq20ehecd3ezc438l6uh4r8epaakn4lsqv4qgr3ks4yxngyflq339lza456xt8uly085umq3gwql3qyfge0ec03dezeg8xulz33ntlj8yd7dcra9564zrsqqqqqqqqqqqqqqq5qqqqqqqqqqqqqayjedltzjqqqqqq9yq3n2s3894qsfwwvj3szk4yplg4fkw68nwzlwyc23457qx6v7xe38znuha72km6a2qv0gfq9syypz6g3kyz34nfrl7lm6c3rushzxey3a55ecjgs6qp2vz8q78j336k0sgz2rxjcsxs6s3lnngq9xeqn9pzy53n50p4ulcdvkx8dye7h8xgxpvjyg928m2txk2knl0zzfl7j82c6lq7xqlx83ey7z4aux9pjp4sp7\(dq,
  \(dqchanges\(dq: {}
}
.EE
.PP
