.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-AUTOCLEAN-ONCE" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-autoclean-once -- A single deletion of old invoices/payments/forwards
.SH
SYNOPSIS
.LP
\fBautoclean-once\fR \fIsubsystem\fR \fIage\fR 
.SH
DESCRIPTION
.LP
The \fBautoclean-once\fR RPC command tell the \fCautoclean\fR plugin to do a single sweep to delete old entries. This is a manual alternative (or addition) to the various \fCautoclean-...-age\fR parameters which cause autoclean to run once per hour: see lightningd-config(5).
.IP "\(bu" 2
\fBsubsystem\fR (string) (one of \(dqsucceededforwards\(dq, \(dqfailedforwards\(dq, \(dqsucceededpays\(dq, \(dqfailedpays\(dq, \(dqpaidinvoices\(dq, \(dqexpiredinvoices\(dq): What subsystem to clean. Currently supported subsystems are:
.RS
.IP "\(bu" 2
\fCfailedforwards\fR: routed payments which did not succeed (\fCfailed\fR or \fClocal_failed\fR in listforwards \fCstatus\fR).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fCsucceededforwards\fR: routed payments which succeeded (\fCsettled\fR in listforwards \fCstatus\fR).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fCfailedpays\fR: payment attempts which did not succeed (\fCfailed\fR in listpays \fCstatus\fR).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fCsucceededpays\fR: payment attempts which succeeded (\fCcomplete\fR in listpays \fCstatus\fR).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fCexpiredinvoices\fR: invoices which were not paid (and cannot be) (\fCexpired\fR in listinvoices \fCstatus\fR).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fCpaidinvoices\fR: invoices which were paid (\fCpaid\fR in listinvoices status).
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBage\fR (u64): Non-zero number in seconds. How many seconds old an entry must be to delete it.
.SH
RETURN VALUE
.LP
On success, an object containing \fBautoclean\fR is returned. It is an object containing:
.IP "\(bu" 2
\fBsucceededforwards\fR (object, optional):
.RS
.IP "\(bu" 2
\fBcleaned\fR (u64): Total number of deletions done this run.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBuncleaned\fR (u64): The total number of entries \fInot\fR deleted this run.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfailedforwards\fR (object, optional):
.RS
.IP "\(bu" 2
\fBcleaned\fR (u64): Total number of deletions done this run.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBuncleaned\fR (u64): The total number of entries \fInot\fR deleted this run.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBsucceededpays\fR (object, optional):
.RS
.IP "\(bu" 2
\fBcleaned\fR (u64): Total number of deletions done this run.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBuncleaned\fR (u64): The total number of entries \fInot\fR deleted this run.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfailedpays\fR (object, optional):
.RS
.IP "\(bu" 2
\fBcleaned\fR (u64): Total number of deletions done this run.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBuncleaned\fR (u64): The total number of entries \fInot\fR deleted this run.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpaidinvoices\fR (object, optional):
.RS
.IP "\(bu" 2
\fBcleaned\fR (u64): Total number of deletions done this run.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBuncleaned\fR (u64): The total number of entries \fInot\fR deleted this run.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBexpiredinvoices\fR (object, optional):
.RS
.IP "\(bu" 2
\fBcleaned\fR (u64): Total number of deletions done this run.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBuncleaned\fR (u64): The total number of entries \fInot\fR deleted this run.
.RE
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightningd-config(5), lightning-autoclean-status(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli autoclean-once \(dqfailedpays\(dq \(dq1\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:autoclean-once#1\(dq,
  \(dqmethod\(dq: \(dqautoclean-once\(dq,
  \(dqparams\(dq: [
    \(dqfailedpays\(dq,
    1
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqautoclean\(dq: {
    \(dqfailedpays\(dq: {
      \(dqcleaned\(dq: 0,
      \(dquncleaned\(dq: 7
    }
  }
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli autoclean-once \(dqsucceededpays\(dq \(dq1\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:autoclean-once#2\(dq,
  \(dqmethod\(dq: \(dqautoclean-once\(dq,
  \(dqparams\(dq: [
    \(dqsucceededpays\(dq,
    1
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqautoclean\(dq: {
    \(dqsucceededpays\(dq: {
      \(dqcleaned\(dq: 7,
      \(dquncleaned\(dq: 0
    }
  }
}
.EE
.PP
