.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-LISTFUNDS" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-listfunds -- Command showing all funds currently managed by the Core Lightning node
.SH
SYNOPSIS
.LP
\fBlistfunds\fR [\fIspent\fR] 
.SH
DESCRIPTION
.LP
The \fBlistfunds\fR RPC command displays all funds available, either in unspent outputs (UTXOs) in the internal wallet or funds locked in currently open channels.
.IP "\(bu" 2
\fBspent\fR (boolean, optional): If True, then the \fIoutputs\fR will include spent outputs in addition to the unspent ones. The default is False.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBoutputs\fR (array of objects):
.RS
.IP "\(bu" 2
\fBtxid\fR (txid): The ID of the spendable transaction.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoutput\fR (u32): The index within \fItxid\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat): The amount of the output.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBscriptpubkey\fR (hex): The scriptPubkey of the output.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqunconfirmed\(dq, \(dqconfirmed\(dq, \(dqspent\(dq, \(dqimmature\(dq)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBreserved\fR (boolean): Whether this UTXO is currently reserved for an in-flight tx.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBaddress\fR (string, optional): The bitcoin address of the output.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBredeemscript\fR (hex, optional): The redeemscript, only if it's p2sh-wrapped.
.RE
.IP
If \fBstatus\fR is \(dqconfirmed\(dq:
- \fBblockheight\fR (u32): Block height where it was confirmed.
.IP
If \fBreserved\fR is \(dqtrue\(dq:
- \fBreserved_to_block\fR (u32): Block height where reservation will expire.
.IP "\(bu" 2
\fBchannels\fR (array of objects):
.RS
.IP "\(bu" 2
\fBpeer_id\fR (pubkey): The peer with which the channel is opened.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBour_amount_msat\fR (msat): Available satoshis on our node's end of the channel.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat): Total channel value.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfunding_txid\fR (txid): Funding transaction id.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfunding_output\fR (u32): The 0-based index of the output in the funding transaction.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBconnected\fR (boolean): Whether the channel peer is connected.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstate\fR (string) (one of \(dqOPENINGD\(dq, \(dqCHANNELD_AWAITING_LOCKIN\(dq, \(dqCHANNELD_NORMAL\(dq, \(dqCHANNELD_SHUTTING_DOWN\(dq, \(dqCLOSINGD_SIGEXCHANGE\(dq, \(dqCLOSINGD_COMPLETE\(dq, \(dqAWAITING_UNILATERAL\(dq, \(dqFUNDING_SPEND_SEEN\(dq, \(dqONCHAIN\(dq, \(dqDUALOPEND_OPEN_INIT\(dq, \(dqDUALOPEND_AWAITING_LOCKIN\(dq, \(dqDUALOPEND_OPEN_COMMITTED\(dq, \(dqDUALOPEND_OPEN_COMMIT_READY\(dq): The channel state, in particular \fCCHANNELD_NORMAL\fR means the channel can be used normally.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBchannel_id\fR (hash): The full channel_id (funding txid Xored with output number). \fI(added v23.05)\fR
.RE
.IP
If \fBstate\fR is \(dqCHANNELD_NORMAL\(dq:
- \fBshort_channel_id\fR (short_channel_id): Short channel id of channel.
.IP
If \fBstate\fR is \(dqCHANNELD_SHUTTING_DOWN\(dq, \(dqCLOSINGD_SIGEXCHANGE\(dq, \(dqCLOSINGD_COMPLETE\(dq, \(dqAWAITING_UNILATERAL\(dq, \(dqFUNDING_SPEND_SEEN\(dq or \(dqONCHAIN\(dq:
- \fBshort_channel_id\fR (short_channel_id, optional): Short channel id of channel (only if funding reached lockin depth before closing).
.SH
AUTHOR
.LP
Felix <\fIfixone@gmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-newaddr(7), lightning-fundchannel(7), lightning-withdraw(7), lightning-listtransactions(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listfunds
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listfunds#1\(dq,
  \(dqmethod\(dq: \(dqlistfunds\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqoutputs\(dq: [
    {
      \(dqtxid\(dq: \(dq9454852bb62e304ee8933662284e10bd22a7f3710c262da4c94bdcc8b05ae407\(dq,
      \(dqoutput\(dq: 0,
      \(dqamount_msat\(dq: 19993653000,
      \(dqscriptpubkey\(dq: \(dq51206c27e1956acfa61e68292c80908880e813450f754132e8a2ac471a86bf1326b5\(dq,
      \(dqaddress\(dq: \(dqbcrt1pdsn7r9t2e7npu6pf9jqfpzyqaqf52rm4gyew3g4vgudgd0cny66srft45s\(dq,
      \(dqstatus\(dq: \(dqconfirmed\(dq,
      \(dqblockheight\(dq: 103,
      \(dqreserved\(dq: false
    },
    {
      \(dqtxid\(dq: \(dq7547ffc11396c62852104f7100d5ca27a2b9c0d5d43d08122147b2b03eb157a5\(dq,
      \(dqoutput\(dq: 0,
      \(dqamount_msat\(dq: 2000000000,
      \(dqscriptpubkey\(dq: \(dq00149fb67bfcefee6cb7db4c7e55d9c6bfd749e31d1e\(dq,
      \(dqaddress\(dq: \(dqbcrt1qn7m8hl80aekt0k6v0e2an34l6ay7x8g703x07y\(dq,
      \(dqstatus\(dq: \(dqconfirmed\(dq,
      \(dqblockheight\(dq: 108,
      \(dqreserved\(dq: false
    },
    {
      \(dqtxid\(dq: \(dq737d6835ddafd515ba9e9def733bb4e4211f6053a32b1422bf1c8cc240850f96\(dq,
      \(dqoutput\(dq: 0,
      \(dqamount_msat\(dq: 198995073000,
      \(dqscriptpubkey\(dq: \(dq512035f1184f6b470c9df347da62c4b28e7ec9ee10b220bac3accd22209def0036ea\(dq,
      \(dqaddress\(dq: \(dqbcrt1pxhc3snmtguxfmu68mf3vfv5w0my7uy9jyzav8txdygsfmmcqxm4q0mms62\(dq,
      \(dqstatus\(dq: \(dqconfirmed\(dq,
      \(dqblockheight\(dq: 109,
      \(dqreserved\(dq: false
    }
  ],
  \(dqchannels\(dq: [
    {
      \(dqpeer_id\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqconnected\(dq: true,
      \(dqstate\(dq: \(dqCHANNELD_NORMAL\(dq,
      \(dqchannel_id\(dq: \(dq252d1b0a1e57895e84137f28cf19ab2c35847e284c112fefdecc7afeaa5c1de7\(dq,
      \(dqshort_channel_id\(dq: \(dq109x1x1\(dq,
      \(dqour_amount_msat\(dq: 490518792,
      \(dqamount_msat\(dq: 1000000000,
      \(dqfunding_txid\(dq: \(dq737d6835ddafd515ba9e9def733bb4e4211f6053a32b1422bf1c8cc240850f96\(dq,
      \(dqfunding_output\(dq: 1
    }
  ]
}
.EE
.PP
