.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-WAITANYINVOICE" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-waitanyinvoice -- Command for waiting for payments
.SH
SYNOPSIS
.LP
\fBwaitanyinvoice\fR [\fIlastpay_index\fR] [\fItimeout\fR] 
.SH
DESCRIPTION
.LP
The \fBwaitanyinvoice\fR RPC command waits until an invoice is paid, then returns a single entry as per \fBlistinvoices\fR. It will not return for any invoices paid prior to or including the \fIlastpay_index\fR.
.PP
This is usually called iteratively: once with no arguments, then repeatedly with the returned \fIpay_index\fR entry. This ensures that no paid invoice is missed. The \fIpay_index\fR is a monotonically-increasing number assigned to an invoice when it gets paid. The first valid \fIpay_index\fR is 1.
.IP "\(bu" 2
\fBlastpay_index\fR (u64, optional): Ignores any invoices paid prior to or including this index. 0 is equivalent to not specifying and negative value is invalid.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtimeout\fR (u64, optional): If specified, wait at most that number of seconds, which must be an integer. If the specified \fItimeout\fR is reached, this command will return with an error. You can specify this to 0 so that \fBwaitanyinvoice\fR will return immediately with an error if no pending invoice is available yet. If unspecified, this command will wait indefinitely.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBlabel\fR (string): Unique label supplied at invoice creation.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdescription\fR (string): Description used in the invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The hash of the \fIpayment_preimage\fR which will prove payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqpaid\(dq, \(dqexpired\(dq): Whether it's paid or expired.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBexpires_at\fR (u64): UNIX timestamp of when it will become / became unpayable.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcreated_index\fR (u64): 1-based index indicating order this invoice was created in. \fI(added v23.08)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): The amount required to pay this invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt11\fR (string, optional): The BOLT11 string (always present unless \fIbolt12\fR is).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt12\fR (string, optional): The BOLT12 string (always present unless \fIbolt11\fR is).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBupdated_index\fR (u64, optional): 1-based index indicating order this invoice was changed (only present if it has changed since creation). \fI(added v23.08)\fR
.LP
If \fBstatus\fR is \(dqpaid\(dq:
- \fBpay_index\fR (u64): Unique incrementing index for this payment.
- \fBamount_received_msat\fR (msat): The amount actually received (could be slightly greater than \fIamount_msat\fR, since clients may overpay).
- \fBpaid_at\fR (u64): UNIX timestamp of when it was paid.
- \fBpayment_preimage\fR (secret): Proof of payment.
- \fBpaid_outpoint\fR (object, optional): Outpoint this invoice was paid with. \fI(added v23.11)\fR:
- \fBtxid\fR (txid): ID of the transaction that paid the invoice. \fI(added v23.11)\fR
- \fBoutnum\fR (u32): The 0-based output number of the transaction that paid the invoice. \fI(added v23.11)\fR
.SH
ERRORS
.LP
The following error codes may occur:
.IP "\(bu" 2
904: The \fItimeout\fR was reached without an invoice being paid.
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-waitinvoice(7), lightning-listinvoices(7), lightning-delinvoice(7), lightning-invoice(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli waitanyinvoice
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:waitanyinvoice#1\(dq,
  \(dqmethod\(dq: \(dqwaitanyinvoice\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqlabel\(dq: \(dqlbl balance l1 to l2\(dq,
  \(dqbolt11\(dq: \(dqlnbcrt5m1pn2s39ksp53sknyy2mxxurt4y0wqgp730z0cnm0vz3zmzth8p79xsrtmg5llxspp5dp94v59nm6c99jf7lc07zmnhqw6kyujx3mkdav7643dczgtdedfqdpcv3jhxcmjd9c8g6t0dcs8xetwvss8xmmdv5s8xct5wvsxcvfqw3hjqmpjxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqdz9cftkxe6kcqfddyrvr7j57ulsfxxxkgkjyhr3k77n8v59mzs5rmuexz9lxusyhhehlemd9ujclgahln8e0n8y86stc7u8uys6mjqgqerm6q4\(dq,
  \(dqpayment_hash\(dq: \(dq684b5650b3deb052c93efe1fe16e7703b56272468eecdeb3daac5b81216dcb52\(dq,
  \(dqamount_msat\(dq: 500000000,
  \(dqstatus\(dq: \(dqpaid\(dq,
  \(dqpay_index\(dq: 1,
  \(dqamount_received_msat\(dq: 500000000,
  \(dqpaid_at\(dq: 1722303671,
  \(dqpayment_preimage\(dq: \(dqbed4140e1db302720d7f9547dc9127d45b115080447cce7e23cfd00b60991831\(dq,
  \(dqdescription\(dq: \(dqdescription send some sats l1 to l2\(dq,
  \(dqexpires_at\(dq: 1722908470,
  \(dqcreated_index\(dq: 1,
  \(dqupdated_index\(dq: 1
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli waitanyinvoice -k \(dqlastpay_index\(dq=1 \(dqtimeout\(dq=0
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:waitanyinvoice#2\(dq,
  \(dqmethod\(dq: \(dqwaitanyinvoice\(dq,
  \(dqparams\(dq: {
    \(dqlastpay_index\(dq: 1,
    \(dqtimeout\(dq: 0
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqlabel\(dq: \(dqlbl_l23\(dq,
  \(dqbolt11\(dq: \(dqlnbcrt1pn2s38zsp5lv49w44a8tvkwtkxfxwts8rnr864u59srp7sxuua3haahdhlhtrqpp5p928w8rmsg2hjeymedcn54vxhsz372qhcedgf003nmsknhx9594sdqcdserxgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqq0vqqqqgqqyqqqqqpqqqqqzsqqc9qxpqysgqt5h8te9lkn0jpdkhkmlkzs80aw7mt5kdm6jxmvddkavt3vj0vakkmfcs0hsde8y8g8za46sch2lp4jxy56u8ve25sgpgcsya0vp92sgphzw570\(dq,
  \(dqpayment_hash\(dq: \(dq0954771c7b821579649bcb713a5586bc051f2817c65a84bdf19ee169dcc5a16b\(dq,
  \(dqstatus\(dq: \(dqpaid\(dq,
  \(dqpay_index\(dq: 2,
  \(dqamount_received_msat\(dq: 9900,
  \(dqpaid_at\(dq: 1722303715,
  \(dqpayment_preimage\(dq: \(dqf3a3b40d63e62785f537aad60f93980914c5639872c7746299a6a1228abbc303\(dq,
  \(dqdescription\(dq: \(dql23 description\(dq,
  \(dqexpires_at\(dq: 1722908514,
  \(dqcreated_index\(dq: 8,
  \(dqupdated_index\(dq: 2
}
.EE
.PP
