.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-RECKLESS" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-reckless -- Issue a command to the reckless plugin manager utility
.SH
SYNOPSIS
.LP
\fBreckless\fR \fIcommand\fR [\fItarget/subcommand\fR] [\fItarget\fR] 
.SH
DESCRIPTION
.LP
The \fBreckless\fR RPC starts a reckless process with the \fIcommand\fR and \fItarget\fR provided.  Node configuration, network, and lightning direrctory are automatically passed to the reckless utility.
.IP "\(bu" 2
\fBcommand\fR (string) (one of \(dqinstall\(dq, \(dquninstall\(dq, \(dqsearch\(dq, \(dqenable\(dq, \(dqdisable\(dq, \(dqsource\(dq, \(dq--version\(dq): Determines which command to pass to reckless
.RS
.IP "\(bu" 2
\fIcommand\fR \fBinstall\fR takes a \fIplugin_name\fR to search for and install a named plugin.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fIcommand\fR \fBuninstall\fR takes a \fIplugin_name\fR and attempts to uninstall a plugin of the same name.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fIcommand\fR \fBsearch\fR takes a \fIplugin_name\fR to search for a named plugin.
\&...
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtarget/subcommand\fR (one of, optional): Target of a reckless command or a subcommand.:
.RS
.IP "\(bu" 2
(string)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
(array)
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtarget\fR (one of, optional): \fIname\fR of a plugin to install/uninstall/search/enable/disable or source to add/remove.:
.RS
.IP "\(bu" 2
(string)
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
(array)
.RE
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBresult\fR (array of strings): Output of the requested reckless command.:
.RS
.IP "\(bu" 2
(string, optional)
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlog\fR (array of strings): Verbose log entries of the requested reckless command.:
.RS
.IP "\(bu" 2
(string, optional)
.RE
.SH
AUTHOR
.LP
Alex Myers <\fIalex@endothermic.dev\fR> is mainly responsible.
.SH
SEE ALSO
.LP
reckless(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli reckless -k \(dqcommand\(dq=\(dqsearch\(dq \(dqtarget/subcommand\(dq=\(dqbackup\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:reckless#1\(dq,
  \(dqmethod\(dq: \(dqreckless\(dq,
  \(dqparams\(dq: {
    \(dqcommand\(dq: \(dqsearch\(dq,
    \(dqtarget/subcommand\(dq: \(dqbackup\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqresult\(dq: [
    \(dqhttps://github.com/lightningd/plugins\(dq
  ],
  \(dqlog\(dq: [
    \(dqDEBUG: Warning: Reckless requires write access\(dq,
    \(dqDEBUG: fetching from gh API: https://api.github.com/repos/lightningd/plugins/contents/\(dq,
    \(dqDEBUG: fetching from gh API: https://api.github.com/repos/lightningd/plugins/git/trees/294f93d7060799439c994daa84f534c4d1458325\(dq,
    \(dqINFO: found backup in source: https://github.com/lightningd/plugins\(dq,
    \(dqDEBUG: entry: None\(dq,
    \(dqDEBUG: sub-directory: backup\(dq
  ]
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli reckless -k \(dqcommand\(dq=\(dqinstall\(dq \(dqtarget/subcommand\(dq='[\(dqsummars\(dq, \(dqcurrecyrate\(dq]'
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:reckless#2\(dq,
  \(dqmethod\(dq: \(dqreckless\(dq,
  \(dqparams\(dq: {
    \(dqcommand\(dq: \(dqinstall\(dq,
    \(dqtarget/subcommand\(dq: [
      \(dqsummars\(dq,
      \(dqcurrecyrate\(dq
    ]
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqresult\(dq: [
    \(dq/tmp/l1/reckless/summars\(dq,
    \(dq/tmp/l1/reckless/currencyrate\(dq
  ],
  \(dqlog\(dq: [
    \(dqDEBUG: Searching for summars\(dq,
    \(dqDEBUG: fetching from gh API: https://api.github.com/repos/lightningd/plugins/contents/\(dq,
    \(dqDEBUG: fetching from gh API: https://api.github.com/repos/lightningd/plugins/git/trees/294f93d7060799439c994daa84f534c4d1458325\(dq,
    \(dqINFO: found summars in source: https://github.com/lightningd/plugins\(dq,
    \(dqDEBUG: entry: None\(dq,
    \(dqDEBUG: sub-directory: summars\(dq,
    \(dqDEBUG: Retrieving summars from https://github.com/lightningd/plugins\(dq,
    \(dqDEBUG: Install requested from InstInfo(summars, https://github.com/lightningd/plugins, None, None, None, summars).\(dq,
    \(dqINFO: cloning Source.GITHUB_REPO InstInfo(summars, https://github.com/lightningd/plugins, None, None, None, summars)\(dq,
    \(dqDEBUG: cloned_src: InstInfo(summars, /tmp/reckless-726255950dyifh_fh/clone, None, Cargo.toml, Cargo.toml, summars/summars)\(dq,
    \(dqDEBUG: using latest commit of default branch\(dq,
    \(dqDEBUG: checked out HEAD: 5e449468bd57db7d0f33178fe0dc867e0da94133\(dq,
    \(dqDEBUG: using installer rust\(dq,
    \(dqDEBUG: creating /tmp/l1/reckless/summars\(dq,
    \(dqDEBUG: creating /tmp/l1/reckless/summars/source\(dq,
    \(dqDEBUG: copying /tmp/reckless-726255950dyifh_fh/clone/summars/summars tree to /tmp/l1/reckless/summars/source/summars\(dq,
    \(dqDEBUG: linking source /tmp/l1/reckless/summars/source/summars/Cargo.toml to /tmp/l1/reckless/summars/Cargo.toml\(dq,
    \(dqDEBUG: InstInfo(summars, /tmp/l1/reckless/summars, None, Cargo.toml, Cargo.toml, source/summars)\(dq,
    \(dqDEBUG: cargo installing from /tmp/l1/reckless/summars/source/summars\(dq,
    \(dqDEBUG: rust project compiled successfully\(dq,
    \(dqINFO: plugin installed: /tmp/l1/reckless/summars\(dq,
    \(dqDEBUG: activating summars\(dq,
    \(dqINFO: summars enabled\(dq,
    \(dqDEBUG: Searching for currencyrate\(dq,
    \(dqDEBUG: fetching from gh API: https://api.github.com/repos/lightningd/plugins/contents/\(dq,
    \(dqDEBUG: fetching from gh API: https://api.github.com/repos/lightningd/plugins/git/trees/294f93d7060799439c994daa84f534c4d1458325\(dq,
    \(dqINFO: found currencyrate in source: https://github.com/lightningd/plugins\(dq,
    \(dqDEBUG: entry: None\(dq,
    \(dqDEBUG: sub-directory: currencyrate\(dq,
    \(dqDEBUG: Retrieving currencyrate from https://github.com/lightningd/plugins\(dq,
    \(dqDEBUG: Install requested from InstInfo(currencyrate, https://github.com/lightningd/plugins, None, None, None, currencyrate).\(dq,
    \(dqINFO: cloning Source.GITHUB_REPO InstInfo(currencyrate, https://github.com/lightningd/plugins, None, None, None, currencyrate)\(dq,
    \(dqDEBUG: cloned_src: InstInfo(currencyrate, /tmp/reckless-192564272t478naxn/clone, None, currencyrate.py, requirements.txt, currencyrate/currencyrate)\(dq,
    \(dqDEBUG: using latest commit of default branch\(dq,
    \(dqDEBUG: checked out HEAD: 5e449468bd57db7d0f33178fe0dc867e0da94133\(dq,
    \(dqDEBUG: using installer python3venv\(dq,
    \(dqDEBUG: creating /tmp/l1/reckless/currencyrate\(dq,
    \(dqDEBUG: creating /tmp/l1/reckless/currencyrate/source\(dq,
    \(dqDEBUG: copying /tmp/reckless-192564272t478naxn/clone/currencyrate/currencyrate tree to /tmp/l1/reckless/currencyrate/source/currencyrate\(dq,
    \(dqDEBUG: linking source /tmp/l1/reckless/currencyrate/source/currencyrate/currencyrate.py to /tmp/l1/reckless/currencyrate/currencyrate.py\(dq,
    \(dqDEBUG: InstInfo(currencyrate, /tmp/l1/reckless/currencyrate, None, currencyrate.py, requirements.txt, source/currencyrate)\(dq,
    \(dqDEBUG: configuring a python virtual environment (pip) in /tmp/l1/reckless/currencyrate/.venv\(dq,
    \(dqDEBUG: virtual environment created in /tmp/l1/reckless/currencyrate/.venv.\(dq,
    \(dqINFO: dependencies installed successfully\(dq,
    \(dqDEBUG: virtual environment for cloned plugin: .venv\(dq,
    \(dqINFO: plugin installed: /tmp/l1/reckless/currencyrate\(dq,
    \(dqDEBUG: activating currencyrate\(dq,
    \(dqINFO: currencyrate enabled\(dq
  ]
}
.EE
.PP
