.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-SENDINVOICE" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-sendinvoice -- Command for send an invoice for an offer
.SH
SYNOPSIS
.LP
\fB(WARNING: experimental-offers only)\fR
.PP
\fBsendinvoice\fR \fIinvreq\fR \fIlabel\fR [\fIamount_msat\fR] [\fItimeout\fR] [\fIquantity\fR] 
.SH
DESCRIPTION
.LP
The \fBsendinvoice\fR RPC command creates and sends an invoice to the issuer of an \fIinvoice_request\fR for it to pay: lightning-invoicerequest(7).
.PP
If \fBfetchinvoice-noconnect\fR is not specified in the configuation, it will connect to the destination in the (currently common!) case where it cannot find a route which supports \fCoption_onion_messages\fR.
.IP "\(bu" 2
\fBinvreq\fR (string): The bolt12 invoice_request string beginning with \fClnr1\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlabel\fR (string): The unique label to use for this invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): Required if the \fIoffer\fR does not specify an amount at all, or specifies it in a different currency. Otherwise you may set it (e.g. to provide a tip). The default is the amount contained in the offer (multiplied by \fIquantity\fR if any).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtimeout\fR (u32, optional): Seconds to wait for the offering node to pay the invoice or return an error. This will also be the timeout on the invoice that is sent. The default is 90 seconds.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBquantity\fR (u64, optional): Quantity is is required if the offer specifies quantity_max, otherwise it is not allowed.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBlabel\fR (string): Unique label supplied at invoice creation.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdescription\fR (string): Description used in the invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The hash of the \fIpayment_preimage\fR which will prove payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqunpaid\(dq, \(dqpaid\(dq, \(dqexpired\(dq): Whether it's paid, unpaid or unpayable.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBexpires_at\fR (u64): UNIX timestamp of when it will become / became unpayable.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcreated_index\fR (u64): 1-based index indicating order this invoice was created in. \fI(added v23.08)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): The amount required to pay this invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt12\fR (string, optional): The BOLT12 string.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBupdated_index\fR (u64, optional): 1-based index indicating order this invoice was changed (only present if it has changed since creation). \fI(added v23.08)\fR
.LP
If \fBstatus\fR is \(dqpaid\(dq:
- \fBpay_index\fR (u64): Unique incrementing index for this payment.
- \fBamount_received_msat\fR (msat): The amount actually received (could be slightly greater than \fIamount_msat\fR, since clients may overpay).
- \fBpaid_at\fR (u64): UNIX timestamp of when it was paid.
- \fBpayment_preimage\fR (secret): Proof of payment.
.SH
ERRORS
.LP
The following error codes may occur:
.IP "\(bu" 2
-1: Catchall nonspecific error.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1002: Offer has expired.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1003: Cannot find a route to the node making the offer.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1004: The node making the offer returned an error message.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
1005: We timed out waiting for the invoice to be paid
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-fetchinvoice(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli sendinvoice -k \(dqinvreq\(dq=\(dqlnr1qqgypua5g7rp293k00s66ayvnv26czst2d5k6urvv5s8getnw3gzqp3zderpzxstt8927ynqg044h0egcd8n5h3n9g0u0v4h8ncc3yg02gps7sjqtqssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e7pq947t0ks7a4yejz8w79x4zj25s3pu6zrnw2e0v2ugdescpcqsq307z4p2dlxe92fv7xd43qut0pjkg4y094hupqyhsj8dlhvmmfng6sv\(dq \(dqlabel\(dq=\(dqtest sendinvoice\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:sendinvoice#1\(dq,
  \(dqmethod\(dq: \(dqsendinvoice\(dq,
  \(dqparams\(dq: {
    \(dqinvreq\(dq: \(dqlnr1qqgypua5g7rp293k00s66ayvnv26czst2d5k6urvv5s8getnw3gzqp3zderpzxstt8927ynqg044h0egcd8n5h3n9g0u0v4h8ncc3yg02gps7sjqtqssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e7pq947t0ks7a4yejz8w79x4zj25s3pu6zrnw2e0v2ugdescpcqsq307z4p2dlxe92fv7xd43qut0pjkg4y094hupqyhsj8dlhvmmfng6sv\(dq,
    \(dqlabel\(dq: \(dqtest sendinvoice\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqlabel\(dq: \(dqtest sendinvoice\(dq,
  \(dqbolt12\(dq: \(dqlni1qqgypua5g7rp293k00s66ayvnv26czst2d5k6urvv5s8getnw3gzqp3zderpzxstt8927ynqg044h0egcd8n5h3n9g0u0v4h8ncc3yg02gps7sjqtqssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e5zvqyehytxx360zptatj4pygsv9kpal8gnkeyd0tpvd6jv5rkv2uqdgcq2s27mvxt0arlnulnmce53cuz00vzaqvgvhpphxgavl89r8zrdhaxqgzpvxkkmwsmxnuwflttmnpc8vtzwlgd3cfty3xwlnlc9r2gcjesguqqv4xey4m7l4wxem27vxyxfhwznlc62kffsd5xncx9w49m4g72u2y7lcl6a3x5cpu52j6gm8q5x0q8k7myxdzrsqqqqqqqqqqqqqqq5qqqqqqqqqqqqqayjedltzjqqqqqq9yq3n2s38p5cq442pq5qpm4ht26v8statwxcrl65uy26c9hx4dvy66f9x665eqqy90tpz25qc0gfqtqggzvmj9nrga83q474e2sjygxzmq7ln5fmvjxh4skxafx2pmx9wqx5v0qsqfkcrpht0d3nnt8txkcgf5wr6gzrlacls2gyrvj5hhwuu98shurrn6ayruunju7k9yu9clvaj354tr064ruuht88q5dj73kzru20uzj\(dq,
  \(dqpayment_hash\(dq: \(dqa003badd6ad30f05f56e3607fd538456b05b9aad6135a494dad5320010af5844\(dq,
  \(dqamount_msat\(dq: 1000000,
  \(dqstatus\(dq: \(dqpaid\(dq,
  \(dqpay_index\(dq: 1,
  \(dqamount_received_msat\(dq: 1000000,
  \(dqpaid_at\(dq: 1722303714,
  \(dqpayment_preimage\(dq: \(dq6f154ed7d108349cb6385eba5f160294ef83862c2c560ba6446b2a3da5c2b3b3\(dq,
  \(dqdescription\(dq: \(dqSimple test\(dq,
  \(dqexpires_at\(dq: 1722303803,
  \(dqcreated_index\(dq: 3,
  \(dqupdated_index\(dq: 1
}
.EE
.PP
