.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-DELPAY" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-delpay -- Command for removing a completed or failed payment
.SH
SYNOPSIS
.LP
\fBdelpay\fR \fIpayment_hash\fR \fIstatus\fR [\fIpartid\fR \fIgroupid\fR] 
.SH
DESCRIPTION
.LP
The \fBdelpay\fR RPC command deletes a payment with the given \fCpayment_hash\fR if its status is either \fCcomplete\fR or \fCfailed\fR. If \fIpartid\fR and \fIgroupid\fR are not specified, all payment parts with matchin status are deleted.
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The unique identifier of a payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqcomplete\(dq, \(dqfailed\(dq): Expected status of the payment. Only deletes if the payment status matches. Deleting a \fCpending\fR payment will return an error.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpartid\fR (u64, optional): Specific partid to delete (must be paired with \fIgroupid\fR).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBgroupid\fR (u64, optional): Specific groupid to delete (must be paired with \fIpartid\fR).
.SH
RETURN VALUE
.LP
The returned format is the same as lightning-listsendpays(7). If the payment is a multi-part payment (MPP) the command return a list of payments will be returned -- one payment object for each partid.
On success, an object containing \fBpayments\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBcreated_index\fR (u64): 1-based index indicating order this payment was created in. \fI(added v23.11)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBid\fR (u64): Old synonym for created_index.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The hash of the \fIpayment_preimage\fR which will prove payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqpending\(dq, \(dqfailed\(dq, \(dqcomplete\(dq): Status of the payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_sent_msat\fR (msat): The amount we actually sent, including fees.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcreated_at\fR (u64): The UNIX timestamp showing when this payment was initiated.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpartid\fR (u64, optional): Unique ID within this (multi-part) payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdestination\fR (pubkey, optional): The final destination of the payment if known.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): The amount the destination received, if known.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBupdated_index\fR (u64, optional): 1-based index indicating order this payment was changed (only present if it has changed since creation). \fI(added v23.11)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcompleted_at\fR (u64, optional): The UNIX timestamp showing when this payment was completed.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBgroupid\fR (u64, optional): Grouping key to disambiguate multiple attempts to pay an invoice or the same payment_hash.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_preimage\fR (secret, optional): Proof of payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlabel\fR (string, optional): The label, if given to sendpay.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt11\fR (string, optional): The bolt11 string (if pay supplied one).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt12\fR (string, optional): The bolt12 string (if supplied for pay: \fBexperimental-offers\fR only).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBerroronion\fR (hex, optional): The error onion returned on failure, if any.
.SH
ERRORS
.LP
On failure, an error is returned. If the lightning process fails before responding, the
caller should use lightning-listsentpays(7) or lightning-listpays(7) to query whether this payment was deleted or not.
.PP
The following error codes may occur:
.IP "\(bu" 2
-32602: Parameter missed or malformed;
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
211: Payment status mismatch. Check the correct status via \fBpaystatus\fR;
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
208: Payment with payment_hash not found.
.SH
AUTHOR
.LP
Vincenzo Palazzo <\fIvincenzo.palazzo@protonmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-listpays(7), lightning-listsendpays(7), lightning-paystatus(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli delpay -k \(dqpayment_hash\(dq=\(dq684b5650b3deb052c93efe1fe16e7703b56272468eecdeb3daac5b81216dcb52\(dq \(dqstatus\(dq=\(dqcomplete\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:delpay#1\(dq,
  \(dqmethod\(dq: \(dqdelpay\(dq,
  \(dqparams\(dq: {
    \(dqpayment_hash\(dq: \(dq684b5650b3deb052c93efe1fe16e7703b56272468eecdeb3daac5b81216dcb52\(dq,
    \(dqstatus\(dq: \(dqcomplete\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpayments\(dq: [
    {
      \(dqcreated_index\(dq: 1,
      \(dqid\(dq: 1,
      \(dqpayment_hash\(dq: \(dq684b5650b3deb052c93efe1fe16e7703b56272468eecdeb3daac5b81216dcb52\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 1,
      \(dqdestination\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqamount_msat\(dq: 500000000,
      \(dqamount_sent_msat\(dq: 500000000,
      \(dqcreated_at\(dq: 1722303670,
      \(dqcompleted_at\(dq: 1722303671,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dqbed4140e1db302720d7f9547dc9127d45b115080447cce7e23cfd00b60991831\(dq,
      \(dqbolt11\(dq: \(dqlnbcrt5m1pn2s39ksp53sknyy2mxxurt4y0wqgp730z0cnm0vz3zmzth8p79xsrtmg5llxspp5dp94v59nm6c99jf7lc07zmnhqw6kyujx3mkdav7643dczgtdedfqdpcv3jhxcmjd9c8g6t0dcs8xetwvss8xmmdv5s8xct5wvsxcvfqw3hjqmpjxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqdz9cftkxe6kcqfddyrvr7j57ulsfxxxkgkjyhr3k77n8v59mzs5rmuexz9lxusyhhehlemd9ujclgahln8e0n8y86stc7u8uys6mjqgqerm6q4\(dq
    }
  ]
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli delpay \(dq25af7c1858066685212846e0d976263dde0ddbf1a7dc517a652853641dcf81fb\(dq \(dqfailed\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:delpay#2\(dq,
  \(dqmethod\(dq: \(dqdelpay\(dq,
  \(dqparams\(dq: [
    \(dq25af7c1858066685212846e0d976263dde0ddbf1a7dc517a652853641dcf81fb\(dq,
    \(dqfailed\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpayments\(dq: [
    {
      \(dqcreated_index\(dq: 20,
      \(dqid\(dq: 20,
      \(dqpayment_hash\(dq: \(dq25af7c1858066685212846e0d976263dde0ddbf1a7dc517a652853641dcf81fb\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 19,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 50000000,
      \(dqamount_sent_msat\(dq: 50000501,
      \(dqcreated_at\(dq: 1722303803,
      \(dqcompleted_at\(dq: 1722303806,
      \(dqstatus\(dq: \(dqfailed\(dq,
      \(dqbolt11\(dq: \(dqlnbcrt500u1pn2s3fwsp5e6nltgzk3yqn5033r6z2q32pzduys3zs5dtzc5cjs60ppcgytrsqpp5ykhhcxzcqeng2gfggmsdja3x8h0qmkl35lw9z7n99pfkg8w0s8asdqcdsenvgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqq0vqqqqgqqyqqqqqpqqqqqzsqqc9qxpqysgqwn7uwmy3x8u9c4ea0ka0yp3qvs0w9m7459g65kalm553vusctq8kseaph7tav4ryjfghnhu0ggjhhkrqmafarqkdsrzsk8stcvdmpmcqwfsajc\(dq
    }
  ]
}
.EE
.PP
\fBExample 3\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli delpay -k \(dqpayment_hash\(dq=\(dq647252f7e45fce7bb964523206874f40f58fbb7b208bc08967caa0e2404990c9\(dq \(dqstatus\(dq=\(dqfailed\(dq \(dqgroupid\(dq=1 \(dqpartid\(dq=2
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:delpay#3\(dq,
  \(dqmethod\(dq: \(dqdelpay\(dq,
  \(dqparams\(dq: {
    \(dqpayment_hash\(dq: \(dq647252f7e45fce7bb964523206874f40f58fbb7b208bc08967caa0e2404990c9\(dq,
    \(dqstatus\(dq: \(dqfailed\(dq,
    \(dqgroupid\(dq: 1,
    \(dqpartid\(dq: 2
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpayments\(dq: [
    {
      \(dqcreated_index\(dq: 17,
      \(dqid\(dq: 17,
      \(dqpayment_hash\(dq: \(dq647252f7e45fce7bb964523206874f40f58fbb7b208bc08967caa0e2404990c9\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 16,
      \(dqpartid\(dq: 2,
      \(dqdestination\(dq: \(dq0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199\(dq,
      \(dqamount_msat\(dq: 1000000,
      \(dqamount_sent_msat\(dq: 1000000,
      \(dqcreated_at\(dq: 1722303798,
      \(dqcompleted_at\(dq: 1722303799,
      \(dqstatus\(dq: \(dqfailed\(dq
    }
  ]
}
.EE
.PP
