.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-LISTPAYS" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-listpays -- Command for querying payment status
.SH
SYNOPSIS
.LP
\fBlistpays\fR [\fIbolt11\fR] [\fIpayment_hash\fR] [\fIstatus\fR] 
.SH
DESCRIPTION
.LP
The \fBlistpay\fR RPC command gets the status of all \fIpay\fR commands, or a single one if either \fIbolt11\fR or \fIpayment_hash\fR was specified.
.IP "\(bu" 2
\fBbolt11\fR (string, optional): Bolt11 string to get the payment details.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash, optional): Payment hash to get the payment details.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string, optional) (one of \(dqpending\(dq, \(dqcomplete\(dq, \(dqfailed\(dq): To filter the payment by status.
.SH
RETURN VALUE
.LP
On success, an object containing \fBpays\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The hash of the \fIpayment_preimage\fR which will prove payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqpending\(dq, \(dqfailed\(dq, \(dqcomplete\(dq): Status of the payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcreated_at\fR (u64): The UNIX timestamp showing when this payment was initiated.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdestination\fR (pubkey, optional): The final destination of the payment if known.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcompleted_at\fR (u64, optional): The UNIX timestamp showing when this payment was completed.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlabel\fR (string, optional): The label, if given to sendpay.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt11\fR (string, optional): The bolt11 string (if pay supplied one).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdescription\fR (string, optional): The description matching the bolt11 description hash (if pay supplied one).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt12\fR (string, optional): The bolt12 string (if supplied for pay: \fBexperimental-offers\fR only).
.LP
If \fBstatus\fR is \(dqcomplete\(dq:
- \fBamount_sent_msat\fR (msat): The amount of millisatoshi we sent in order to pay (may include fees and not match amount_msat).
- \fBpreimage\fR (secret): Proof of payment.
- \fBamount_msat\fR (msat, optional): The amount of millisatoshi we intended to send to the destination.
- \fBnumber_of_parts\fR (u64, optional): The number of parts for a successful payment (only if more than one).
.PP
If \fBstatus\fR is \(dqfailed\(dq:
- \fBerroronion\fR (hex, optional): The error onion returned on failure, if any.
.PP
The returned array is ordered by increasing \fBcreated_at\fR fields.
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-pay(7), lightning-paystatus(7), lightning-listsendpays(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listpays -k \(dqbolt11\(dq=\(dqlnbcrt500n1pn2s396sp5h5tz6fpm3dxvrlwcnwmfq85v45wfj43mdmplpce6ku2vmfdhrx5qpp50z9w5u57meydx9dpn889mmtkz6tqrfsa65hfwd88ql4hc5hyu70qdqcdsenygryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqt5m8qx0t25a0gygya7u4sxulyyp2dec87pwsxuuwtg0u66c07703g9j6vlwgmlhqk7qgn95qw7allhnuj2m9hf0xkcr2zkaxltv3t6gqjcdpll\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listpays#1\(dq,
  \(dqmethod\(dq: \(dqlistpays\(dq,
  \(dqparams\(dq: {
    \(dqbolt11\(dq: \(dqlnbcrt500n1pn2s396sp5h5tz6fpm3dxvrlwcnwmfq85v45wfj43mdmplpce6ku2vmfdhrx5qpp50z9w5u57meydx9dpn889mmtkz6tqrfsa65hfwd88ql4hc5hyu70qdqcdsenygryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqt5m8qx0t25a0gygya7u4sxulyyp2dec87pwsxuuwtg0u66c07703g9j6vlwgmlhqk7qgn95qw7allhnuj2m9hf0xkcr2zkaxltv3t6gqjcdpll\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpays\(dq: []
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listpays
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listpays#2\(dq,
  \(dqmethod\(dq: \(dqlistpays\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpays\(dq: [
    {
      \(dqbolt11\(dq: \(dqlnbcrt5m1pn2s39hsp50pekdm9axtcfm0ttsxzg2z0738ujk5uc3n0v5rul2y2ghkeh772qpp50a60qe8lg55t0mru27xlvcnpwetu46d0ff60tuj0dr9cged3secqdpcv3jhxcmjd9c8g6t0dcs8xetwvss8xmmdv5s8xct5wvsxcv3qw3hjqmpnxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqcjj3uz0ux4qxt4ev4patfwz44e7ns57tmvxdwzfq2pj5drm5xhk5agm8j2wha32g664a0mw6casy44vfdf76jj38n3669fsjps4jkaqpaydvjr\(dq,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqpayment_hash\(dq: \(dq7f74f064ff4528b7ec7c578df662617657cae9af4a74f5f24f68cb8465b18670\(dq,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqcreated_at\(dq: 1722303671,
      \(dqcompleted_at\(dq: 1722303672,
      \(dqpreimage\(dq: \(dqd9893938f4464933d87f5123a8c09b4e98e106c9c34c1812340c9570d72d16a2\(dq,
      \(dqamount_msat\(dq: 500000000,
      \(dqamount_sent_msat\(dq: 500000000
    },
    {
      \(dqbolt11\(dq: \(dqlnbcrt5m1pn2s39csp59778k5kecnjhyqu7amy99kt8nhu43ap74m8q3xryvqxrjnsrnxpqpp5s3fd8u9xnhgwtqpsq9jtcspzu4dmxvcatpvl2a3dje5055fmqrdqdpcv3jhxcmjd9c8g6t0dcs8xetwvss8xmmdv5s8xct5wvsxcv3qw3hjqmp4xqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jx3rjwmh5d5rmgqqqqqpqqqqqzsqqc9qxpqysgqe4hfa6arms4pz6ajwhq07lhc57g60vrdqyfdsewu84q823m8zqdjtcsv7aun8zqxr86amyz0lclf8pfts0hqy60s9fcvvsjyxnnmpugpjcq9xk\(dq,
      \(dqdestination\(dq: \(dq032cf15d1ad9c4a08d26eab1918f732d8ef8fdc6abb9640bf3db174372c491304e\(dq,
      \(dqpayment_hash\(dq: \(dq8452d3f0a69dd0e580300164bc4022e55bb3331d5859f5762d9668fa513b00da\(dq,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqcreated_at\(dq: 1722303672,
      \(dqcompleted_at\(dq: 1722303673,
      \(dqpreimage\(dq: \(dq576f5426f339b3db80d1b3c3546d6832274171609f25795c64b6cc74aa158d8c\(dq,
      \(dqamount_msat\(dq: 500000000,
      \(dqamount_sent_msat\(dq: 500000000
    },
    {
      \(dqbolt11\(dq: \(dqlnbcrt1u1pn2s3xxsp5xk8hs6zuv0yqhq7hhl0sps6mxuj78pzwryejaljh48vr4htykujqpp593ndc8wrukteld5j4nqnt6tedavh8ezv48dmrkqen3440ajnre5qdqcdsenxgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgq0asve9rdtfd9fe20u5vjujzmm0phpq538z8ndhn5ts62aflhktqn6338e45xcxkyf7askjjq25ksxt4eqarjjame8wfdmau7kq7m4csqs0n32n\(dq,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqpayment_hash\(dq: \(dq2c66dc1dc3e5979fb692acc135e9796f5973e44ca9dbb1d8199c6b57f6531e68\(dq,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqcreated_at\(dq: 1722303688,
      \(dqcompleted_at\(dq: 1722303689,
      \(dqpreimage\(dq: \(dq1ce8370d3a179cee3af25a5a6c7058e8e12033a842efd6d34abae53334bc94bf\(dq,
      \(dqamount_msat\(dq: 100000,
      \(dqamount_sent_msat\(dq: 100000
    },
    {
      \(dqbolt12\(dq: \(dqlni1qqgypua5g7rp293k00s66ayvnv26czst2d5k6urvv5s8getnw3gzqp3zderpzxstt8927ynqg044h0egcd8n5h3n9g0u0v4h8ncc3yg02gps7sjqtqssytfzxcs2xkdy0lml0tzy0jzugmyj8kjn8zfzrgq9fsgurc72x82e5zvqyehytxx360zptatj4pygsv9kpal8gnkeyd0tpvd6jv5rkv2uqdgcq2s27mvxt0arlnulnmce53cuz00vzaqvgvhpphxgavl89r8zrdhaxqgzpvxkkmwsmxnuwflttmnpc8vtzwlgd3cfty3xwlnlc9r2gcjesguqqv4xey4m7l4wxem27vxyxfhwznlc62kffsd5xncx9w49m4g72u2y7lcl6a3x5cpu52j6gm8q5x0q8k7myxdzrsqqqqqqqqqqqqqqq5qqqqqqqqqqqqqayjedltzjqqqqqq9yq3n2s38p5cq442pq5qpm4ht26v8statwxcrl65uy26c9hx4dvy66f9x665eqqy90tpz25qc0gfqtqggzvmj9nrga83q474e2sjygxzmq7ln5fmvjxh4skxafx2pmx9wqx5v0qsqfkcrpht0d3nnt8txkcgf5wr6gzrlacls2gyrvj5hhwuu98shurrn6ayruunju7k9yu9clvaj354tr064ruuht88q5dj73kzru20uzj\(dq,
      \(dqdestination\(dq: \(dq0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518\(dq,
      \(dqpayment_hash\(dq: \(dqa003badd6ad30f05f56e3607fd538456b05b9aad6135a494dad5320010af5844\(dq,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqcreated_at\(dq: 1722303713,
      \(dqcompleted_at\(dq: 1722303714,
      \(dqpreimage\(dq: \(dq6f154ed7d108349cb6385eba5f160294ef83862c2c560ba6446b2a3da5c2b3b3\(dq,
      \(dqamount_msat\(dq: 1000000,
      \(dqamount_sent_msat\(dq: 1000000
    },
    {
      \(dqbolt11\(dq: \(dqlnbcrt1pn2s38zsp5lv49w44a8tvkwtkxfxwts8rnr864u59srp7sxuua3haahdhlhtrqpp5p928w8rmsg2hjeymedcn54vxhsz372qhcedgf003nmsknhx9594sdqcdserxgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqq0vqqqqgqqyqqqqqpqqqqqzsqqc9qxpqysgqt5h8te9lkn0jpdkhkmlkzs80aw7mt5kdm6jxmvddkavt3vj0vakkmfcs0hsde8y8g8za46sch2lp4jxy56u8ve25sgpgcsya0vp92sgphzw570\(dq,
      \(dqdestination\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqpayment_hash\(dq: \(dq0954771c7b821579649bcb713a5586bc051f2817c65a84bdf19ee169dcc5a16b\(dq,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqcreated_at\(dq: 1722303715,
      \(dqcompleted_at\(dq: 1722303715,
      \(dqpreimage\(dq: \(dqf3a3b40d63e62785f537aad60f93980914c5639872c7746299a6a1228abbc303\(dq,
      \(dqamount_msat\(dq: 9900,
      \(dqamount_sent_msat\(dq: 9900
    },
    {
      \(dqbolt11\(dq: \(dqlnbcrt40n1pn2s3xxsp5j329vez86jvxw6543zlcla2fusm7v6h74pf7ftmmyfv6zm9uedlspp5j6xpxmq8cwd305vj2dvd6dh4mkr0s6guvehvyleymedgf4vsm3ysdqaveskjmr9vssxgetnvdexjur5d9hkuxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqk6uwy8pkv42jzhdna3z4vxpwkapdzzpn2tcpjnqj738nlpkjc583l9v72vlskt8y33rr4z3jma32xx7ve0jfy7anvn6r98cr5flhcuqqhr4shx\(dq,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqpayment_hash\(dq: \(dq968c136c07c39b17d1925358dd36f5dd86f8691c666ec27f24de5a84d590dc49\(dq,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqcreated_at\(dq: 1722303719,
      \(dqcompleted_at\(dq: 1722303720,
      \(dqpreimage\(dq: \(dq8815ee921dba644c076f9f879abb520d8539a6913856a439752eaaadff1e21ac\(dq,
      \(dqamount_msat\(dq: 4000,
      \(dqamount_sent_msat\(dq: 4000
    }
  ]
}
.EE
.PP
