.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-PING" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-ping -- Command to check if a node is up.
.SH
SYNOPSIS
.LP
\fBping\fR \fIid\fR [\fIlen\fR] [\fIpongbytes\fR] 
.SH
DESCRIPTION
.LP
The \fBping\fR command checks if the node with \fIid\fR is ready to talk. It currently only works for peers we have a channel with.
.IP "\(bu" 2
\fBid\fR (pubkey): The pubkey of the node to ping.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlen\fR (u16, optional): The length of the ping. The default is 128.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpongbytes\fR (u16, optional): The length of the reply. A value of 65532 to 65535 means \fCdon't reply\fR. The default is 128.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBtotlen\fR (u16): The answer length of the reply message (including header: 0 means no reply expected).
.SH
ERRORS
.LP
On failure, one of the following error codes may be returned:
.IP "\(bu" 2
-32602: Error in given parameters or we're already waiting for a ping response from peer.
.SH
AUTHOR
.LP
Vincenzo Palazzo <\fIvincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page,
but many others did the hard work of actually implementing this rpc command.
.SH
SEE ALSO
.LP
lightning-connect(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli ping -k \(dqid\(dq=\(dq0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518\(dq \(dqlen\(dq=128 \(dqpongbytes\(dq=128
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:ping#1\(dq,
  \(dqmethod\(dq: \(dqping\(dq,
  \(dqparams\(dq: {
    \(dqid\(dq: \(dq0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518\(dq,
    \(dqlen\(dq: 128,
    \(dqpongbytes\(dq: 128
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqtotlen\(dq: 132
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli ping -k \(dqid\(dq=\(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq \(dqlen\(dq=1000 \(dqpongbytes\(dq=65535
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:ping#2\(dq,
  \(dqmethod\(dq: \(dqping\(dq,
  \(dqparams\(dq: {
    \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
    \(dqlen\(dq: 1000,
    \(dqpongbytes\(dq: 65535
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqtotlen\(dq: 0
}
.EE
.PP
