.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-RENEPAYSTATUS" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-renepaystatus -- Command for quering the status of previous renepay attempts
.SH
SYNOPSIS
.LP
\fBrenepaystatus\fR [\fIinvstring\fR] 
.SH
DESCRIPTION
.LP
Command \fIadded\fR in v23.08.
.PP
The \fBrenepaystatus\fR RPC command queries the payment plugin \fBrenepay\fR for the status of previous payment attempts.
.PP
This command always succeeds.
.IP "\(bu" 2
\fBinvstring\fR (string, optional): If specified, the command will return a list of payment attempts whose invoice matches \fIinvstring\fR, otherwise all payments with be listed.
.SH
RETURN VALUE
.LP
On success, an object containing \fBpaystatus\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBbolt11\fR (string): Invoice string BOLT11.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The hash of the \fIpayment_preimage\fR which will prove payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcreated_at\fR (number): The UNIX timestamp showing when this payment was initiated.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBgroupid\fR (u32): The id for this payment attempt.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat): Amount the recipient received.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqcomplete\(dq, \(dqpending\(dq, \(dqfailed\(dq): Status of payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_preimage\fR (secret, optional): The proof of payment: SHA256 of this \fBpayment_hash\fR (for completed payments only).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBparts\fR (u32, optional): How many attempts this took.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_sent_msat\fR (msat, optional): Total amount we sent including fees (for completed payments only).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdestination\fR (pubkey, optional): The final destination of the payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBnotes\fR (array of strings, optional): A list of messages for debugging purposes.:
.RS
.IP "\(bu" 2
(string, optional): A message generated by renepay.
.RE
.SH
AUTHOR
.LP
Eduardo Quintana-Miranda <\fIeduardo.quintana@pm.me\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-renepay(7), lightning-listpays(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli renepaystatus -k \(dqinvstring\(dq=\(dqlnbcrt1pn2s3xxsp5xvccgadvepzypat5v8u8tstwdvn9ez4908h7ntl4s0ggx76ug4cqpp50qwurth9swdlzphjvjc2qm8sws8jcu0u28y4vt5s7nhr3js0c3vsdqcdserzgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqw4qfxj30wqn2m2qmcfz2gs6ttszdhkc0kjqk0mgg59tj2cy90wcke4tjzmzakrkvcgqgf3367j47q5g2ruuw67cxaqxm2t4m42yecsqp92jzs7\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:renepaystatus#1\(dq,
  \(dqmethod\(dq: \(dqrenepaystatus\(dq,
  \(dqparams\(dq: {
    \(dqinvstring\(dq: \(dqlnbcrt1pn2s3xxsp5xvccgadvepzypat5v8u8tstwdvn9ez4908h7ntl4s0ggx76ug4cqpp50qwurth9swdlzphjvjc2qm8sws8jcu0u28y4vt5s7nhr3js0c3vsdqcdserzgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqw4qfxj30wqn2m2qmcfz2gs6ttszdhkc0kjqk0mgg59tj2cy90wcke4tjzmzakrkvcgqgf3367j47q5g2ruuw67cxaqxm2t4m42yecsqp92jzs7\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpaystatus\(dq: [
    {
      \(dqbolt11\(dq: \(dqlnbcrt1pn2s3xxsp5xvccgadvepzypat5v8u8tstwdvn9ez4908h7ntl4s0ggx76ug4cqpp50qwurth9swdlzphjvjc2qm8sws8jcu0u28y4vt5s7nhr3js0c3vsdqcdserzgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqw4qfxj30wqn2m2qmcfz2gs6ttszdhkc0kjqk0mgg59tj2cy90wcke4tjzmzakrkvcgqgf3367j47q5g2ruuw67cxaqxm2t4m42yecsqp92jzs7\(dq,
      \(dqamount_msat\(dq: 400000,
      \(dqpayment_hash\(dq: \(dq781dc1aee5839bf106f264b0a06cf0740f2c71fc51c9562e90f4ee38ca0fc459\(dq,
      \(dqdestination\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqcreated_at\(dq: 1722303718.0730329,
      \(dqgroupid\(dq: 1,
      \(dqparts\(dq: 2,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dqaf67b48518e78e157db404d13cb42987c31e034634203d10b224302b05fc6c90\(dq,
      \(dqamount_sent_msat\(dq: 400000
    }
  ]
}
.EE
.PP
