.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-PARSEFEERATE" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-parsefeerate -- Command for parsing a feerate string to a feerate
.SH
SYNOPSIS
.LP
\fBparsefeerate\fR \fIfeerate_str\fR 
.SH
DESCRIPTION
.LP
The \fBparsefeerate\fR command returns the current feerate for any valid \fIfeerate_str\fR. This is useful for finding the current feerate that a \fBfundpsbt\fR or \fButxopsbt\fR command might use.
.IP "\(bu" 2
\fBfeerate_str\fR (string): The feerate string to parse.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBperkw\fR (u32, optional): Value of \fIfeerate_str\fR in kilosipa.
.SH
ERRORS
.LP
The \fBparsefeerate\fR command will error if the \fIfeerate_str\fR format is not recognized.
.IP "\(bu" 2
-32602: If the given parameters are wrong.
.SH
TRIVIA
.LP
In CLN we like to call the weight unit \(dqsipa\(dq in honor of Pieter Wuille, who uses the name \(dqsipa\(dq on IRC and elsewhere. Internally we call the \fIperkw\fR style as \(dqfeerate per kilosipa\(dq.
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli parsefeerate \(dqunilateral_close\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:parsefeerate#1\(dq,
  \(dqmethod\(dq: \(dqparsefeerate\(dq,
  \(dqparams\(dq: [
    \(dqunilateral_close\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqperkw\(dq: 11000
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli parsefeerate \(dq9999perkw\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:parsefeerate#2\(dq,
  \(dqmethod\(dq: \(dqparsefeerate\(dq,
  \(dqparams\(dq: [
    \(dq9999perkw\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqperkw\(dq: 9999
}
.EE
.PP
\fBExample 3\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli parsefeerate \(dq10000\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:parsefeerate#3\(dq,
  \(dqmethod\(dq: \(dqparsefeerate\(dq,
  \(dqparams\(dq: [
    10000
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqperkw\(dq: 2500
}
.EE
.PP
\fBExample 4\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli parsefeerate \(dqurgent\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:parsefeerate#4\(dq,
  \(dqmethod\(dq: \(dqparsefeerate\(dq,
  \(dqparams\(dq: [
    \(dqurgent\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqperkw\(dq: 11000
}
.EE
.PP
