.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-ADDPSBTOUTPUT" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-addpsbtoutput -- Command to populate PSBT outputs from the wallet
.SH
SYNOPSIS
.LP
\fBaddpsbtoutput\fR \fIsatoshi\fR [\fIinitialpsbt\fR] [\fIlocktime\fR] [\fIdestination\fR] 
.SH
DESCRIPTION
.LP
Command \fIadded\fR in v23.11.
.PP
\fCaddpsbtoutput\fR is a low-level RPC command which creates or modifies a PSBT by adding a single output of amount \fIsatoshi\fR.
.PP
This is used to receive funds into the on-chain wallet interactively using PSBTs.
.IP "\(bu" 2
\fBsatoshi\fR (sat): The satoshi value of the output. It can be a whole number, a whole number ending in \fIsat\fR, or a number with 1 to 8 decimal places ending in \fIbtc\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBinitialpsbt\fR (string, optional): Base 64 encoded PSBT to add the output to. If not specified, one will be generated automatically.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlocktime\fR (u32, optional): If not set, it is set to a recent block height (if no initial psbt is specified).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdestination\fR (string, optional): If it is not set, an internal address is generated.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBpsbt\fR (string): Unsigned PSBT which fulfills the parameters given.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBestimated_added_weight\fR (u32): The estimated weight of the added output.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoutnum\fR (u32): The 0-based number where the output was placed.
.SH
AUTHOR
.LP
Dusty <<@dusty_daemon>> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-fundpsbt(7), lightning-utxopsbt(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: Here is a command to make a PSBT with a 1,000,000 sat output that leads to the on-chain wallet:
.PP
Request:
.LP
.EX
$ lightning-cli addpsbtoutput -k \(dqsatoshi\(dq=1000000 \(dqlocktime\(dq=111
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:addpsbtoutput#1\(dq,
  \(dqmethod\(dq: \(dqaddpsbtoutput\(dq,
  \(dqparams\(dq: {
    \(dqsatoshi\(dq: 1000000,
    \(dqlocktime\(dq: 111
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQEBAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAA==\(dq,
  \(dqestimated_added_weight\(dq: 172,
  \(dqoutnum\(dq: 0
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli addpsbtoutput \(dq3333333\(dq \(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQECAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAAEDCNXcMgAAAAAAAQQiUSA2cYCeVGcxdSZII2urHpalr5osmF2lPbYRaw1nKyPcmQA=\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:addpsbtoutput#2\(dq,
  \(dqmethod\(dq: \(dqaddpsbtoutput\(dq,
  \(dqparams\(dq: [
    3333333,
    \(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQECAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAAEDCNXcMgAAAAAAAQQiUSA2cYCeVGcxdSZII2urHpalr5osmF2lPbYRaw1nKyPcmQA=\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQECAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAAEDCNXcMgAAAAAAAQQiUSA2cYCeVGcxdSZII2urHpalr5osmF2lPbYRaw1nKyPcmQA=\(dq,
  \(dqestimated_added_weight\(dq: 172,
  \(dqoutnum\(dq: 1
}
.EE
.PP
\fBExample 3\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli addpsbtoutput -k \(dqsatoshi\(dq=3333333 \(dqinitialpsbt\(dq=\(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQECAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAAEDCNXcMgAAAAAAAQQiUSA2cYCeVGcxdSZII2urHpalr5osmF2lPbYRaw1nKyPcmQA=\(dq \(dqdestination\(dq=\(dqbcrt1p52spc7t99z0wu444elxahxzkcu86gakzvnfp7ugudf567am2uspsuneuq9\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:addpsbtoutput#3\(dq,
  \(dqmethod\(dq: \(dqaddpsbtoutput\(dq,
  \(dqparams\(dq: {
    \(dqsatoshi\(dq: 3333333,
    \(dqinitialpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQECAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAAEDCNXcMgAAAAAAAQQiUSA2cYCeVGcxdSZII2urHpalr5osmF2lPbYRaw1nKyPcmQA=\(dq,
    \(dqdestination\(dq: \(dqbcrt1p52spc7t99z0wu444elxahxzkcu86gakzvnfp7ugudf567am2uspsuneuq9\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEbwAAAAEEAQABBQEDAQYBAwH7BAIAAAAAAQMIQEIPAAAAAAABBCJRIO7yw3zIUblRUcdhCLSjdFxJsYHu2s0Y29bT0bGAGdcbAAEDCNXcMgAAAAAAAQQiUSA2cYCeVGcxdSZII2urHpalr5osmF2lPbYRaw1nKyPcmQABAwjV3DIAAAAAAAEEIlEgoqAceWUonu5Wtc/N25hWxw+kdsJk0h9xHGppr3dq5AMA\(dq,
  \(dqestimated_added_weight\(dq: 172,
  \(dqoutnum\(dq: 2
}
.EE
.PP
