.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-CONNECT" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-connect -- Command for connecting to another lightning node
.SH
SYNOPSIS
.LP
\fBconnect\fR \fIid\fR [\fIhost\fR] [\fIport\fR] 
.SH
DESCRIPTION
.LP
The \fBconnect\fR RPC command establishes a new connection with another node in the Lightning Network.
.PP
Connecting to a node is just the first step in opening a channel with another node. Once the peer is connected a channel can be opened with lightning-fundchannel(7).
.PP
If there are active channels with the peer, \fBconnect\fR returns once all the subdaemons are in place to handle the channels, not just once it's connected.
.IP "\(bu" 2
\fBid\fR (string): The target node's public key. As a convenience, \fIid\fR may be of the form \fIid@host\fR or \fIid@host:port\fR. In this case, the \fIhost\fR and \fIport\fR parameters must be omitted. This can fail if your C-lightning node is a fresh install that has not connected to any peers yet (your node has no gossip yet), or if the target \fIid\fR is a fresh install that has no channels yet (nobody will gossip about a node until it has one published channel).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBhost\fR (string, optional): The peer's hostname or IP address. If \fIhost\fR is not specified (or doesn't work), the connection will be attempted to an IP belonging to \fIid\fR obtained through gossip with other already connected peers. If \fIhost\fR begins with a \fC/\fR it is interpreted as a local path and the connection will be made to that local socket (see \fBbind-addr\fR in lightningd-config(5)).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBport\fR (u16, optional): The peer's port number. If not specified, the \fIport\fR depends on the current network:
.RS
.IP "\(bu" 2
bitcoin \fBmainnet\fR: 9735.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
bitcoin \fBtestnet\fR: 19735.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
bitcoin \fBsignet\fR: 39735.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
bitcoin \fBregtest\fR: 19846.
.RE
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBid\fR (pubkey): The peer we connected to.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfeatures\fR (hex): BOLT 9 features bitmap offered by peer.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdirection\fR (string) (one of \(dqin\(dq, \(dqout\(dq): Whether they initiated connection or we did.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBaddress\fR (object): Address information (mainly useful if \fBdirection\fR is \fIout\fR).:
.RS
.IP "\(bu" 2
\fBtype\fR (string) (one of \(dqlocal socket\(dq, \(dqipv4\(dq, \(dqipv6\(dq, \(dqtorv2\(dq, \(dqtorv3\(dq): Type of connection (\fItorv2\fR/\fItorv3\fR only if \fBdirection\fR is \fIout\fR).
.RE
.IP
If \fBtype\fR is \(dqlocal socket\(dq:
- \fBsocket\fR (string): Socket filename.
.IP
If \fBtype\fR is \(dqipv4\(dq, \(dqipv6\(dq, \(dqtorv2\(dq or \(dqtorv3\(dq:
- \fBaddress\fR (string): Address in expected format for \fBtype\fR.
- \fBport\fR (u16): Port number.
.SH
ERRORS
.LP
On failure, one of the following errors will be returned:
.IP "\(bu" 2
400: Unable to connect, no address known for peer
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
401: If some addresses are known but connecting to all of them failed, the message will contain details about the failures
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
402: If the peer disconnected while we were connecting
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
-32602: If the given parameters are wrong
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible. Felix <\fIfixone@gmail.com\fR> is the original author of this manpage.
.SH
SEE ALSO
.LP
lightning-fundchannel(7), lightning-listpeers(7), lightning-listchannels(7), lightning-disconnect(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli connect -k \(dqid\(dq=\(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq \(dqhost\(dq=\(dqlocalhost\(dq \(dqport\(dq=41219
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:connect#1\(dq,
  \(dqmethod\(dq: \(dqconnect\(dq,
  \(dqparams\(dq: {
    \(dqid\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
    \(dqhost\(dq: \(dqlocalhost\(dq,
    \(dqport\(dq: 41219
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqid\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
  \(dqfeatures\(dq: \(dq08a0802a8a59a1\(dq,
  \(dqdirection\(dq: \(dqout\(dq,
  \(dqaddress\(dq: {
    \(dqtype\(dq: \(dqipv4\(dq,
    \(dqaddress\(dq: \(dq127.0.0.1\(dq,
    \(dqport\(dq: 41219
  }
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli connect -k \(dqid\(dq=\(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq \(dqhost\(dq=\(dqlocalhost\(dq \(dqport\(dq=34785
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:connect#2\(dq,
  \(dqmethod\(dq: \(dqconnect\(dq,
  \(dqparams\(dq: {
    \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
    \(dqhost\(dq: \(dqlocalhost\(dq,
    \(dqport\(dq: 34785
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
  \(dqfeatures\(dq: \(dq08a0802a8a59a1\(dq,
  \(dqdirection\(dq: \(dqout\(dq,
  \(dqaddress\(dq: {
    \(dqtype\(dq: \(dqipv4\(dq,
    \(dqaddress\(dq: \(dq127.0.0.1\(dq,
    \(dqport\(dq: 34785
  }
}
.EE
.PP
