.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-BKPR-INSPECT" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-bkpr-inspect -- Command to show onchain footprint of a channel
.SH
SYNOPSIS
.LP
\fBbkpr-inspect\fR \fIaccount\fR 
.SH
DESCRIPTION
.LP
The \fBbkpr-inspect\fR RPC command lists all known on-chain transactions and associated events for the provided account. Useful for inspecting unilateral closes for a given channel account. Only valid for channel accounts.
.IP "\(bu" 2
\fBaccount\fR (string): Channel account to inspect.
.SH
RETURN VALUE
.LP
On success, an object containing \fBtxs\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBtxid\fR (txid): Transaction id.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfees_paid_msat\fR (msat): Amount paid in sats for this tx.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoutputs\fR (array of objects):
.RS
.IP "\(bu" 2
\fBaccount\fR (string): Account this output affected.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoutnum\fR (u32): Index of output.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoutput_value_msat\fR (msat): Value of the output.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcurrency\fR (string): Human-readable bech32 part for this coin type.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcredit_msat\fR (msat, optional): Amount credited to account.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdebit_msat\fR (msat, optional): Amount debited from account.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoriginating_account\fR (string, optional): Account this output originated from.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBoutput_tag\fR (string, optional): Description of output creation event.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBspend_tag\fR (string, optional): Description of output spend event.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBspending_txid\fR (txid, optional): Transaction this output was spent in.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_id\fR (hex, optional): Lightning payment identifier. For an htlc, this will be the preimage.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBblockheight\fR (u32, optional): Blockheight of transaction.
.SH
AUTHOR
.LP
Lisa Neigut <\fIniftynei@gmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-listbalances(7), lightning-listfunds(7), lightning-listpeers(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli bkpr-inspect -k \(dqaccount\(dq=\(dqa397dd9b3e44afcb67f3f3ce1d649b74a8ade63e35505985e4cc1828634f69a2\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:bkpr-inspect#1\(dq,
  \(dqmethod\(dq: \(dqbkpr-inspect\(dq,
  \(dqparams\(dq: {
    \(dqaccount\(dq: \(dqa397dd9b3e44afcb67f3f3ce1d649b74a8ade63e35505985e4cc1828634f69a2\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqtxs\(dq: [
    {
      \(dqtxid\(dq: \(dqcd23f0517eefc27194981253eb07b19b055246df77033e052c66eaf2bbb00483\(dq,
      \(dqblockheight\(dq: 111,
      \(dqfees_paid_msat\(dq: 4927000,
      \(dqoutputs\(dq: [
        {
          \(dqaccount\(dq: \(dqa397dd9b3e44afcb67f3f3ce1d649b74a8ade63e35505985e4cc1828634f69a2\(dq,
          \(dqoutnum\(dq: 0,
          \(dqoutput_tag\(dq: \(dqchannel_open\(dq,
          \(dqoutput_value_msat\(dq: 1000000000,
          \(dqcredit_msat\(dq: 1000000000,
          \(dqcurrency\(dq: \(dqbcrt\(dq,
          \(dqspend_tag\(dq: \(dqchannel_close\(dq,
          \(dqspending_txid\(dq: \(dq70e0466dc2e74f25afe38df6a85d5e8857079873a6d5eda4732806a7ac427305\(dq,
          \(dqdebit_msat\(dq: 489818898
        }
      ]
    },
    {
      \(dqtxid\(dq: \(dq70e0466dc2e74f25afe38df6a85d5e8857079873a6d5eda4732806a7ac427305\(dq,
      \(dqblockheight\(dq: 121,
      \(dqfees_paid_msat\(dq: 2895898,
      \(dqoutputs\(dq: [
        {
          \(dqaccount\(dq: \(dqwallet\(dq,
          \(dqoutnum\(dq: 0,
          \(dqoutput_tag\(dq: \(dqdeposit\(dq,
          \(dqoutput_value_msat\(dq: 486923000,
          \(dqcredit_msat\(dq: 486923000,
          \(dqcurrency\(dq: \(dqbcrt\(dq
        },
        {
          \(dqaccount\(dq: \(dqexternal\(dq,
          \(dqoutnum\(dq: 1,
          \(dqoutput_tag\(dq: \(dqto_them\(dq,
          \(dqoutput_value_msat\(dq: 510181000,
          \(dqcredit_msat\(dq: 510181000,
          \(dqcurrency\(dq: \(dqbcrt\(dq,
          \(dqoriginating_account\(dq: \(dqa397dd9b3e44afcb67f3f3ce1d649b74a8ade63e35505985e4cc1828634f69a2\(dq
        }
      ]
    }
  ]
}
.EE
.PP
