.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-OPENCHANNEL_BUMP" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-openchannel_bump -- Command to initiate a channel RBF
.SH
SYNOPSIS
.LP
\fBopenchannel_bump\fR \fIchannel_id\fR \fIamount\fR \fIinitialpsbt\fR [\fIfunding_feerate\fR] 
.SH
DESCRIPTION
.LP
\fCopenchannel_bump\fR is a RPC command which initiates a channel RBF (Replace-By-Fee) for the specified channel. It uses the openchannel protocol which allows for interactive transaction construction.
.PP
Warning: bumping a leased channel will lose the lease.
.IP "\(bu" 2
\fBchannel_id\fR (hash): Id of the channel to RBF.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount\fR (sat): Satoshi value that we will contribute to the channel. This value will be _added_ to the provided PSBT in the output which is encumbered by the 2-of-2 script for this channel.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBinitialpsbt\fR (string): The funded, incomplete PSBT that specifies the UTXOs and change output for our channel contribution. It can be updated, see \fCopenchannel_update\fR; \fIinitialpsbt\fR must have at least one input. Must have the Non-Witness UTXO (PSBT_IN_NON_WITNESS_UTXO) set for every input. An error (code 309) will be returned if this requirement is not met.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfunding_feerate\fR (feerate, optional): Feerate for the funding transaction. The default is 1/64th greater than the last feerate used for this channel.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBchannel_id\fR (hash): The channel id of the channel.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBchannel_type\fR (object): Channel_type as negotiated with peer. \fI(added v24.02)\fR:
.RS
.IP "\(bu" 2
\fBbits\fR (array of u32s): Each bit set in this channel_type. \fI(added v24.02)\fR:
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
(u32, optional): Bit number.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBnames\fR (array of strings): Feature name for each bit set in this channel_type. Note that \fIanchors_zero_fee_htlc_tx\fR is a deprecated synonym for \fIanchors\fR. \fI(added v24.02)\fR:
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
(string, optional) (one of \(dqstatic_remotekey/even\(dq, \(dqanchor_outputs/even\(dq, \(dqanchors_zero_fee_htlc_tx/even\(dq, \(dqanchors/even\(dq, \(dqscid_alias/even\(dq, \(dqzeroconf/even\(dq): Name of feature bit.
.RE
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpsbt\fR (string): The (incomplete) PSBT of the RBF transaction.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcommitments_secured\fR (boolean) (always \fIfalse\fR): Whether the \fIpsbt\fR is complete.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfunding_serial\fR (u64): The serial_id of the funding output in the \fIpsbt\fR.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBrequires_confirmed_inputs\fR (boolean, optional): Does peer require confirmed inputs in psbt?
.LP
If the peer does not support \fCoption_dual_fund\fR, this command will return an error.
.PP
If the channel is not in a state that is eligible for RBF, this command will return an error.
.SH
ERRORS
.LP
On error the returned object will contain \fCcode\fR and \fCmessage\fR properties, with \fCcode\fR being one of the following:
.IP "\(bu" 2
-32602: If the given parameters are wrong.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
-1: Catchall nonspecific error.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
300: The amount exceeded the maximum configured funding amount.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
301: The provided PSBT cannot afford the funding amount.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
305: Peer is not connected.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
309: PSBT missing required fields
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
311: Unknown channel id.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
312: Channel in an invalid state
.SH
AUTHOR
.LP
Lisa Neigut <\fIniftynei@gmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-openchannel_init(7), lightning-openchannel_update(7), lightning-openchannel_signed(7), lightning-openchannel_abort(7), lightning-fundchannel_start(7), lightning-fundchannel_complete(7), lightning-fundchannel(7), lightning-fundpsbt(7), lightning-utxopsbt(7), lightning-multifundchannel(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli openchannel_bump \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq \(dq1000000\(dq \(dqcHNidP8BAF4CAAAAAbMFPNMIQ2TqCB0v5X8scJh4eVEhwcG3I1h2iff11Pu/AQAAAAD9////AUFZ3AsAAAAAIlEgO+E35aPNS3YQRaiMByjTJDUYNvBO1Z39o3m42EZGUreYAAAAAAEAcQIAAAABl0vCMXO3vKmwYNrBKr0bsVjo7Wmj501PavWRmxX1dywAAAAAAP3///8Ceh/00gAAAAAWABSauB3UBW2CVXly9l1sU6aMmVAq+ADC6wsAAAAAFgAUA8/shxXh9ASjbsAR5COPhjKfkJyXAAAAAQEfAMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnAAA\(dq \(dq15000perkw\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:openchannel_bump#1\(dq,
  \(dqmethod\(dq: \(dqopenchannel_bump\(dq,
  \(dqparams\(dq: [
    \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq,
    1000000,
    \(dqcHNidP8BAF4CAAAAAbMFPNMIQ2TqCB0v5X8scJh4eVEhwcG3I1h2iff11Pu/AQAAAAD9////AUFZ3AsAAAAAIlEgO+E35aPNS3YQRaiMByjTJDUYNvBO1Z39o3m42EZGUreYAAAAAAEAcQIAAAABl0vCMXO3vKmwYNrBKr0bsVjo7Wmj501PavWRmxX1dywAAAAAAP3///8Ceh/00gAAAAAWABSauB3UBW2CVXly9l1sU6aMmVAq+ADC6wsAAAAAFgAUA8/shxXh9ASjbsAR5COPhjKfkJyXAAAAAQEfAMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnAAA\(dq,
    \(dq15000perkw\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqchannel_id\(dq: \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq,
  \(dqpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEmAAAAAEEAQEBBQECAQYBAwH7BAIAAAAAAQBxAgAAAAGXS8Ixc7e8qbBg2sEqvRuxWOjtaaPnTU9q9ZGbFfV3LAAAAAAA/f///wJ6H/TSAAAAABYAFJq4HdQFbYJVeXL2XWxTpoyZUCr4AMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnJcAAAABAR8AwusLAAAAABYAFAPP7IcV4fQEo27AEeQjj4Yyn5CcAQ4gswU80whDZOoIHS/lfyxwmHh5USHBwbcjWHaJ9/XU+78BDwQBAAAAARAE/f///wz8CWxpZ2h0bmluZwEITP+kZdFBsOIAAQMIQEIPAAAAAAABBCIAIMm8XAY8rvv3pseBRAe1YntPgai1bsvpMsaC+cusDRnfDPwJbGlnaHRuaW5nAQg8VGAuu93kPAABAwhBWdwLAAAAAAEEIlEgO+E35aPNS3YQRaiMByjTJDUYNvBO1Z39o3m42EZGUrcM/AlsaWdodG5pbmcBCJhXLSQQ2IEcAA==\(dq,
  \(dqchannel_type\(dq: {
    \(dqbits\(dq: [
      12,
      22
    ],
    \(dqnames\(dq: [
      \(dqstatic_remotekey/even\(dq,
      \(dqanchors/even\(dq
    ]
  },
  \(dqcommitments_secured\(dq: false,
  \(dqfunding_serial\(dq: 4347205294156014600,
  \(dqrequires_confirmed_inputs\(dq: false
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli openchannel_bump -k \(dqchannel_id\(dq=\(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq \(dqamount\(dq=1000000 \(dqinitialpsbt\(dq=\(dqcHNidP8BAF4CAAAAAbMFPNMIQ2TqCB0v5X8scJh4eVEhwcG3I1h2iff11Pu/AQAAAAD9////AUFZ3AsAAAAAIlEgO+E35aPNS3YQRaiMByjTJDUYNvBO1Z39o3m42EZGUreYAAAAAAEAcQIAAAABl0vCMXO3vKmwYNrBKr0bsVjo7Wmj501PavWRmxX1dywAAAAAAP3///8Ceh/00gAAAAAWABSauB3UBW2CVXly9l1sU6aMmVAq+ADC6wsAAAAAFgAUA8/shxXh9ASjbsAR5COPhjKfkJyXAAAAAQEfAMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnAAA\(dq \(dqfunding_feerate\(dq=\(dq15000perkw\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:openchannel_bump#2\(dq,
  \(dqmethod\(dq: \(dqopenchannel_bump\(dq,
  \(dqparams\(dq: {
    \(dqchannel_id\(dq: \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq,
    \(dqamount\(dq: 1000000,
    \(dqinitialpsbt\(dq: \(dqcHNidP8BAF4CAAAAAbMFPNMIQ2TqCB0v5X8scJh4eVEhwcG3I1h2iff11Pu/AQAAAAD9////AUFZ3AsAAAAAIlEgO+E35aPNS3YQRaiMByjTJDUYNvBO1Z39o3m42EZGUreYAAAAAAEAcQIAAAABl0vCMXO3vKmwYNrBKr0bsVjo7Wmj501PavWRmxX1dywAAAAAAP3///8Ceh/00gAAAAAWABSauB3UBW2CVXly9l1sU6aMmVAq+ADC6wsAAAAAFgAUA8/shxXh9ASjbsAR5COPhjKfkJyXAAAAAQEfAMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnAAA\(dq,
    \(dqfunding_feerate\(dq: \(dq15000perkw\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqchannel_id\(dq: \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq,
  \(dqpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEmAAAAAEEAQEBBQECAQYBAwH7BAIAAAAAAQBxAgAAAAGXS8Ixc7e8qbBg2sEqvRuxWOjtaaPnTU9q9ZGbFfV3LAAAAAAA/f///wJ6H/TSAAAAABYAFJq4HdQFbYJVeXL2XWxTpoyZUCr4AMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnJcAAAABAR8AwusLAAAAABYAFAPP7IcV4fQEo27AEeQjj4Yyn5CcAQ4gswU80whDZOoIHS/lfyxwmHh5USHBwbcjWHaJ9/XU+78BDwQBAAAAARAE/f///wz8CWxpZ2h0bmluZwEIQCsNB0i02NIAAQMIQVncCwAAAAABBCJRIDvhN+WjzUt2EEWojAco0yQ1GDbwTtWd/aN5uNhGRlK3DPwJbGlnaHRuaW5nAQgwkgFDAVpmeAABAwhAQg8AAAAAAAEEIgAgybxcBjyu+/emx4FEB7Vie0+BqLVuy+kyxoL5y6wNGd8M/AlsaWdodG5pbmcBCI9GsPn+O/M0AA==\(dq,
  \(dqchannel_type\(dq: {
    \(dqbits\(dq: [
      12,
      22
    ],
    \(dqnames\(dq: [
      \(dqstatic_remotekey/even\(dq,
      \(dqanchors/even\(dq
    ]
  },
  \(dqcommitments_secured\(dq: false,
  \(dqfunding_serial\(dq: 10324133783552127000,
  \(dqrequires_confirmed_inputs\(dq: false
}
.EE
.PP
\fBExample 3\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli openchannel_bump \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq \(dq2000000\(dq \(dqcHNidP8BAF4CAAAAAbMFPNMIQ2TqCB0v5X8scJh4eVEhwcG3I1h2iff11Pu/AQAAAAD9////AWINzQsAAAAAIlEgyRg+3pEh88b9FJiCLEenYCcyJ2ackJUIhDusW72BP2iYAAAAAAEAcQIAAAABl0vCMXO3vKmwYNrBKr0bsVjo7Wmj501PavWRmxX1dywAAAAAAP3///8Ceh/00gAAAAAWABSauB3UBW2CVXly9l1sU6aMmVAq+ADC6wsAAAAAFgAUA8/shxXh9ASjbsAR5COPhjKfkJyXAAAAAQEfAMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnAAA\(dq \(dq18750perkw\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:openchannel_bump#3\(dq,
  \(dqmethod\(dq: \(dqopenchannel_bump\(dq,
  \(dqparams\(dq: [
    \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq,
    2000000,
    \(dqcHNidP8BAF4CAAAAAbMFPNMIQ2TqCB0v5X8scJh4eVEhwcG3I1h2iff11Pu/AQAAAAD9////AWINzQsAAAAAIlEgyRg+3pEh88b9FJiCLEenYCcyJ2ackJUIhDusW72BP2iYAAAAAAEAcQIAAAABl0vCMXO3vKmwYNrBKr0bsVjo7Wmj501PavWRmxX1dywAAAAAAP3///8Ceh/00gAAAAAWABSauB3UBW2CVXly9l1sU6aMmVAq+ADC6wsAAAAAFgAUA8/shxXh9ASjbsAR5COPhjKfkJyXAAAAAQEfAMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnAAA\(dq,
    \(dq18750perkw\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqchannel_id\(dq: \(dqb020c1c6818daf024954c9ee578caad058cbcae7dd75b2c4d38b8f6f81901ff5\(dq,
  \(dqpsbt\(dq: \(dqcHNidP8BAgQCAAAAAQMEmAAAAAEEAQEBBQECAQYBAwH7BAIAAAAAAQBxAgAAAAGXS8Ixc7e8qbBg2sEqvRuxWOjtaaPnTU9q9ZGbFfV3LAAAAAAA/f///wJ6H/TSAAAAABYAFJq4HdQFbYJVeXL2XWxTpoyZUCr4AMLrCwAAAAAWABQDz+yHFeH0BKNuwBHkI4+GMp+QnJcAAAABAR8AwusLAAAAABYAFAPP7IcV4fQEo27AEeQjj4Yyn5CcAQ4gswU80whDZOoIHS/lfyxwmHh5USHBwbcjWHaJ9/XU+78BDwQBAAAAARAE/f///wz8CWxpZ2h0bmluZwEIwRR1uu1r8GoAAQMIgIQeAAAAAAABBCIAIMm8XAY8rvv3pseBRAe1YntPgai1bsvpMsaC+cusDRnfDPwJbGlnaHRuaW5nAQjdRD+FoUsRIAABAwhiDc0LAAAAAAEEIlEgyRg+3pEh88b9FJiCLEenYCcyJ2ackJUIhDusW72BP2gM/AlsaWdodG5pbmcBCPN/JmOnjFW4AA==\(dq,
  \(dqchannel_type\(dq: {
    \(dqbits\(dq: [
      12,
      22
    ],
    \(dqnames\(dq: [
      \(dqstatic_remotekey/even\(dq,
      \(dqanchors/even\(dq
    ]
  },
  \(dqcommitments_secured\(dq: false,
  \(dqfunding_serial\(dq: 15943938423967650000,
  \(dqrequires_confirmed_inputs\(dq: false
}
.EE
.PP
