.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-LISTNODES" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-listnodes -- Command to get the list of nodes in the known network.
.SH
SYNOPSIS
.LP
\fBlistnodes\fR [\fIid\fR] 
.SH
DESCRIPTION
.LP
The \fBlistnodes\fR command returns nodes the node has learned about via gossip messages, or a single one if the node \fIid\fR was specified.
.IP "\(bu" 2
\fBid\fR (pubkey, optional): The public key of the node to list.
.SH
RETURN VALUE
.LP
On success, an object containing \fBnodes\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBnodeid\fR (pubkey): The public key of the node.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlast_timestamp\fR (u32, optional): A node_announcement has been received for this node (UNIX timestamp).
.LP
If \fBlast_timestamp\fR is present:
- \fBalias\fR (string) (up to 32 characters): The fun alias this node advertized.
- \fBcolor\fR (hex) (always 6 characters): The favorite RGB color this node advertized.
- \fBfeatures\fR (hex): BOLT #9 features bitmap this node advertized.
- \fBaddresses\fR (array of objects): The addresses this node advertized.:
- \fBtype\fR (string) (one of \(dqdns\(dq, \(dqipv4\(dq, \(dqipv6\(dq, \(dqtorv2\(dq, \(dqtorv3\(dq): Type of connection (until 23.08, \fCwebsocket\fR was also allowed).
- \fBport\fR (u16): Port number.
.LP
.EX
If **type** is \(dqdns\(dq, \(dqipv4\(dq, \(dqipv6\(dq, \(dqtorv2\(dq or \(dqtorv3\(dq:
  - **address** (string): Address in expected format for **type**.
.EE
.PP
If \fBoption_will_fund\fR is present:
- \fBoption_will_fund\fR (object):
- \fBlease_fee_base_msat\fR (msat): The fixed fee for a lease (whole number of satoshis).
- \fBlease_fee_basis\fR (u32): The proportional fee in basis points (parts per 10,000) for a lease.
- \fBfunding_weight\fR (u32): The onchain weight you'll have to pay for a lease.
- \fBchannel_fee_max_base_msat\fR (msat): The maximum base routing fee this node will charge during the lease.
- \fBchannel_fee_max_proportional_thousandths\fR (u32): The maximum proportional routing fee this node will charge during the lease (in thousandths, not millionths like channel_update).
- \fBcompact_lease\fR (hex): The lease as represented in the node_announcement.
.SH
ERRORS
.LP
On failure, one of the following error codes may be returned:
.IP "\(bu" 2
-32602: Error in given parameters.
.SH
AUTHOR
.LP
Vincenzo Palazzo <\fIvincenzo.palazzo@protonmail.com\fR> wrote the initial version of this man page,
but many others did the hard work of actually implementing this rpc command.
.SH
SEE ALSO
.LP
lightning-listchannels(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listnodes -k \(dqid\(dq=\(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listnodes#1\(dq,
  \(dqmethod\(dq: \(dqlistnodes\(dq,
  \(dqparams\(dq: {
    \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqnodes\(dq: [
    {
      \(dqnodeid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqalias\(dq: \(dqHOPPINGFIRE--190-g5fd2f9c-modded\(dq,
      \(dqcolor\(dq: \(dq035d2b\(dq,
      \(dqlast_timestamp\(dq: 1722303669,
      \(dqfeatures\(dq: \(dq88a0802a8a59a1\(dq,
      \(dqaddresses\(dq: []
    }
  ]
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listnodes
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listnodes#2\(dq,
  \(dqmethod\(dq: \(dqlistnodes\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqnodes\(dq: [
    {
      \(dqnodeid\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqalias\(dq: \(dqSILENTARTIST-190-g5fd2f9c-modded\(dq,
      \(dqcolor\(dq: \(dq022d22\(dq,
      \(dqlast_timestamp\(dq: 1722303662,
      \(dqfeatures\(dq: \(dq88a0802a8a59a1\(dq,
      \(dqaddresses\(dq: []
    },
    {
      \(dqnodeid\(dq: \(dq0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518\(dq,
      \(dqalias\(dq: \(dqJUNIORBEAM-5-190-g5fd2f9c-modded\(dq,
      \(dqcolor\(dq: \(dq0266e4\(dq,
      \(dqlast_timestamp\(dq: 1722303662,
      \(dqfeatures\(dq: \(dq88a0802a8a59a1\(dq,
      \(dqaddresses\(dq: []
    },
    {
      \(dqnodeid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqalias\(dq: \(dqHOPPINGFIRE--190-g5fd2f9c-modded\(dq,
      \(dqcolor\(dq: \(dq035d2b\(dq,
      \(dqlast_timestamp\(dq: 1722303669,
      \(dqfeatures\(dq: \(dq88a0802a8a59a1\(dq,
      \(dqaddresses\(dq: []
    },
    {
      \(dqnodeid\(dq: \(dq0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199\(dq,
      \(dqalias\(dq: \(dqJUNIORFELONY-190-g5fd2f9c-modded\(dq,
      \(dqcolor\(dq: \(dq0382ce\(dq,
      \(dqlast_timestamp\(dq: 1722303669,
      \(dqfeatures\(dq: \(dq88a0802a8a59a1\(dq,
      \(dqaddresses\(dq: []
    }
  ]
}
.EE
.PP
