.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-LISTSENDPAYS" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-listsendpays -- Low-level command for querying sendpay status
.SH
SYNOPSIS
.LP
\fBlistsendpays\fR [\fIbolt11\fR] [\fIpayment_hash\fR] [\fIstatus\fR] [\fIindex\fR [\fIstart\fR] [\fIlimit\fR]]
.SH
DESCRIPTION
.LP
The \fBlistsendpays\fR RPC command gets the status of all \fIsendpay\fR commands (which is also used by the \fIpay\fR command), or with \fIbolt11\fR or \fIpayment_hash\fR limits results to that specific payment. You cannot specify both. It is possible to filter the payments also by \fIstatus\fR.
.PP
Note that there may be more than one concurrent \fIsendpay\fR command per \fIpay\fR, so this command should be used with caution.
.IP "\(bu" 2
\fBbolt11\fR (string, optional): Bolt11 invoice.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash, optional): The hash of the payment_preimage.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string, optional) (one of \(dqpending\(dq, \(dqcomplete\(dq, \(dqfailed\(dq): Whether the invoice has been paid, pending, or failed.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBindex\fR (string, optional) (one of \(dqcreated\(dq, \(dqupdated\(dq): If neither bolt11 or payment_hash is specified, \fCindex\fR controls ordering, by \fCcreated\fR (default) or \fCupdated\fR. \fI(added v23.11)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstart\fR (u64, optional): If \fCindex\fR is specified, \fCstart\fR may be specified to start from that value, which is generally returned from lightning-wait(7). \fI(added v23.11)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlimit\fR (u32, optional): If \fCindex\fR is specified, \fClimit\fR can be used to specify the maximum number of entries to return. \fI(added v23.11)\fR
.SH
RETURN VALUE
.LP
Note that the returned array is ordered by increasing \fIid\fR.
On success, an object containing \fBpayments\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBcreated_index\fR (u64): 1-based index indicating order this payment was created in. \fI(added v23.11)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBid\fR (u64): Old synonym for created_index.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBgroupid\fR (u64): Grouping key to disambiguate multiple attempts to pay an invoice or the same payment_hash.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpayment_hash\fR (hash): The hash of the \fIpayment_preimage\fR which will prove payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBstatus\fR (string) (one of \(dqpending\(dq, \(dqfailed\(dq, \(dqcomplete\(dq): Status of the payment.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBcreated_at\fR (u64): The UNIX timestamp showing when this payment was initiated.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_sent_msat\fR (msat): The amount sent.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpartid\fR (u64, optional): Part number (for multiple parts to a single payment).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBupdated_index\fR (u64, optional): 1-based index indicating order this payment was changed (only present if it has changed since creation). \fI(added v23.11)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBamount_msat\fR (msat, optional): The amount delivered to destination (if known).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdestination\fR (pubkey, optional): The final destination of the payment if known.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlabel\fR (string, optional): The label, if given to sendpay.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt11\fR (string, optional): The bolt11 string (if pay supplied one).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBdescription\fR (string, optional): The description matching the bolt11 description hash (if pay supplied one).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBbolt12\fR (string, optional): The bolt12 string (if supplied for pay: \fBexperimental-offers\fR only).
.LP
If \fBstatus\fR is \(dqcomplete\(dq:
- \fBpayment_preimage\fR (secret): The proof of payment: SHA256 of this \fBpayment_hash\fR.
- \fBcompleted_at\fR (u64, optional): The UNIX timestamp showing when this payment was completed. \fI(added pre-v0.10.1)\fR
.PP
If \fBstatus\fR is \(dqfailed\(dq:
- \fBerroronion\fR (hex, optional): The onion message returned.
.SH
AUTHOR
.LP
Christian Decker <\fIdecker.christian@gmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-listpays(7), lightning-sendpay(7), lightning-listinvoices(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listsendpays -k \(dqbolt11\(dq=\(dqlnbcrt100n1pn2s396sp5v3en0qa3rrljw4m0wtz88sx99q20rarufhjpfysefhwhs42gvqjqpp56kvvl33d594nsxu0hzhesvazgqzlwv89fnpjcvtlanz3rl7x623qdp9f9h8vmmfvdjjqer9wd3hy6tsw35k7m3qdsenzxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgq7za6z8kx2k5nul45zwttfz2njx3836v69mxqsl4ty9228pyjrkfnkymysy8ygsrrje9qf6j4tpalt5qkqusfp2esrsqc5ak7t4yzajgpezef54\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listsendpays#1\(dq,
  \(dqmethod\(dq: \(dqlistsendpays\(dq,
  \(dqparams\(dq: {
    \(dqbolt11\(dq: \(dqlnbcrt100n1pn2s396sp5v3en0qa3rrljw4m0wtz88sx99q20rarufhjpfysefhwhs42gvqjqpp56kvvl33d594nsxu0hzhesvazgqzlwv89fnpjcvtlanz3rl7x623qdp9f9h8vmmfvdjjqer9wd3hy6tsw35k7m3qdsenzxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgq7za6z8kx2k5nul45zwttfz2njx3836v69mxqsl4ty9228pyjrkfnkymysy8ygsrrje9qf6j4tpalt5qkqusfp2esrsqc5ak7t4yzajgpezef54\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpayments\(dq: [
    {
      \(dqcreated_index\(dq: 2,
      \(dqid\(dq: 2,
      \(dqpayment_hash\(dq: \(dqd598cfc62da16b381b8fb8af9833a24005f730e54cc32c317fecc511ffc6d2a2\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 2,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 10000,
      \(dqamount_sent_msat\(dq: 10001,
      \(dqcreated_at\(dq: 1722303675,
      \(dqcompleted_at\(dq: 1722303677,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dq984a10782218478cd39e1f9a16795d756c337662067023a3b690bffdb1593f76\(dq
    }
  ]
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listsendpays
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listsendpays#2\(dq,
  \(dqmethod\(dq: \(dqlistsendpays\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpayments\(dq: [
    {
      \(dqcreated_index\(dq: 1,
      \(dqid\(dq: 1,
      \(dqpayment_hash\(dq: \(dq684b5650b3deb052c93efe1fe16e7703b56272468eecdeb3daac5b81216dcb52\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 1,
      \(dqdestination\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqamount_msat\(dq: 500000000,
      \(dqamount_sent_msat\(dq: 500000000,
      \(dqcreated_at\(dq: 1722303670,
      \(dqcompleted_at\(dq: 1722303671,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dqbed4140e1db302720d7f9547dc9127d45b115080447cce7e23cfd00b60991831\(dq,
      \(dqbolt11\(dq: \(dqlnbcrt5m1pn2s39ksp53sknyy2mxxurt4y0wqgp730z0cnm0vz3zmzth8p79xsrtmg5llxspp5dp94v59nm6c99jf7lc07zmnhqw6kyujx3mkdav7643dczgtdedfqdpcv3jhxcmjd9c8g6t0dcs8xetwvss8xmmdv5s8xct5wvsxcvfqw3hjqmpjxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqdz9cftkxe6kcqfddyrvr7j57ulsfxxxkgkjyhr3k77n8v59mzs5rmuexz9lxusyhhehlemd9ujclgahln8e0n8y86stc7u8uys6mjqgqerm6q4\(dq
    },
    {
      \(dqcreated_index\(dq: 2,
      \(dqid\(dq: 2,
      \(dqpayment_hash\(dq: \(dqd598cfc62da16b381b8fb8af9833a24005f730e54cc32c317fecc511ffc6d2a2\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 2,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 10000,
      \(dqamount_sent_msat\(dq: 10001,
      \(dqcreated_at\(dq: 1722303675,
      \(dqcompleted_at\(dq: 1722303677,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dq984a10782218478cd39e1f9a16795d756c337662067023a3b690bffdb1593f76\(dq
    },
    {
      \(dqcreated_index\(dq: 3,
      \(dqid\(dq: 3,
      \(dqpayment_hash\(dq: \(dq80ff407792947a23f193f9a1968e9a437b071364ae3159f83631335c9a453c1b\(dq,
      \(dqgroupid\(dq: 0,
      \(dqupdated_index\(dq: 3,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 10000,
      \(dqamount_sent_msat\(dq: 10001,
      \(dqcreated_at\(dq: 1722303677,
      \(dqcompleted_at\(dq: 1722303679,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dq0d802c9c611bae611d51afa8ddf396df8ba4e0580a2eccfd1120da97e70482a0\(dq
    },
    {
      \(dqcreated_index\(dq: 4,
      \(dqid\(dq: 4,
      \(dqpayment_hash\(dq: \(dq3b80a3028343b16f8ab7261343eae40ff73ba833b0b7d4dcbfd42a3078dc322b\(dq,
      \(dqgroupid\(dq: 0,
      \(dqupdated_index\(dq: 4,
      \(dqdestination\(dq: \(dq0382ce59ebf18be7d84677c2e35f23294b9992ceca95491fcf8a56c6cb2d9de199\(dq,
      \(dqamount_msat\(dq: 10000000,
      \(dqamount_sent_msat\(dq: 10000202,
      \(dqcreated_at\(dq: 1722303679,
      \(dqcompleted_at\(dq: 1722303682,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dqf76d6b7ef362f33e25eb5571e616f6e539a2c77caf0afa4227d1351546823664\(dq
    },
    {
      \(dqcreated_index\(dq: 5,
      \(dqid\(dq: 5,
      \(dqpayment_hash\(dq: \(dq0458c01fdd3aa0b9829002390301f92083e78dc27bb293bc3e7caee5d4ed7259\(dq,
      \(dqgroupid\(dq: 0,
      \(dqupdated_index\(dq: 5,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 10000,
      \(dqamount_sent_msat\(dq: 10001,
      \(dqcreated_at\(dq: 1722303682,
      \(dqcompleted_at\(dq: 1722303684,
      \(dqstatus\(dq: \(dqfailed\(dq
    },
    {
      \(dqcreated_index\(dq: 6,
      \(dqid\(dq: 6,
      \(dqpayment_hash\(dq: \(dq0458c01fdd3aa0b9829002390301f92083e78dc27bb293bc3e7caee5d4ed7259\(dq,
      \(dqgroupid\(dq: 0,
      \(dqupdated_index\(dq: 6,
      \(dqpartid\(dq: 1,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 10000,
      \(dqamount_sent_msat\(dq: 10001,
      \(dqcreated_at\(dq: 1722303684,
      \(dqcompleted_at\(dq: 1722303686,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dq4dad6dcf625f650a35a8199fbda18ea4f6717cdfadb40e6bed2bf5f96a4742b0\(dq
    },
    {
      \(dqcreated_index\(dq: 7,
      \(dqid\(dq: 7,
      \(dqpayment_hash\(dq: \(dq788aea729ede48d315a199ce5ded76169601a61dd52e9734e707eb7c52e4e79e\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 7,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 50000,
      \(dqamount_sent_msat\(dq: 50001,
      \(dqcreated_at\(dq: 1722303686,
      \(dqcompleted_at\(dq: 1722303688,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dq0e07efd883f66b6b22ec7f2e7116e203c3fecc22eb8596a73eaf06c4befb0641\(dq,
      \(dqbolt11\(dq: \(dqlnbcrt500n1pn2s396sp5h5tz6fpm3dxvrlwcnwmfq85v45wfj43mdmplpce6ku2vmfdhrx5qpp50z9w5u57meydx9dpn889mmtkz6tqrfsa65hfwd88ql4hc5hyu70qdqcdsenygryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqgkjyd3q5dv6gllh77kygly9c3kfy0d9xwyjyxsq2nq3c83u5vw4jqqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqt5m8qx0t25a0gygya7u4sxulyyp2dec87pwsxuuwtg0u66c07703g9j6vlwgmlhqk7qgn95qw7allhnuj2m9hf0xkcr2zkaxltv3t6gqjcdpll\(dq
    },
    {
      \(dqcreated_index\(dq: 8,
      \(dqid\(dq: 8,
      \(dqpayment_hash\(dq: \(dqe445ebcf339db3cba6184330ccc6e4a41e0bb38d237b93c1d2f71958d5a74e13\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 8,
      \(dqamount_sent_msat\(dq: 1002,
      \(dqcreated_at\(dq: 1722303689,
      \(dqcompleted_at\(dq: 1722303692,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dq5e49b520e86aaec8d798bf8107892fb87053d4cb27342518e4588aa609cf35cf\(dq
    },
    {
      \(dqcreated_index\(dq: 9,
      \(dqid\(dq: 9,
      \(dqpayment_hash\(dq: \(dq968c136c07c39b17d1925358dd36f5dd86f8691c666ec27f24de5a84d590dc49\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 9,
      \(dqdestination\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqamount_msat\(dq: 10000,
      \(dqamount_sent_msat\(dq: 10001,
      \(dqcreated_at\(dq: 1722303696,
      \(dqcompleted_at\(dq: 1722303698,
      \(dqstatus\(dq: \(dqfailed\(dq
    },
    {
      \(dqcreated_index\(dq: 10,
      \(dqid\(dq: 10,
      \(dqpayment_hash\(dq: \(dq781dc1aee5839bf106f264b0a06cf0740f2c71fc51c9562e90f4ee38ca0fc459\(dq,
      \(dqgroupid\(dq: 1,
      \(dqupdated_index\(dq: 10,
      \(dqpartid\(dq: 1,
      \(dqdestination\(dq: \(dq022d223620a359a47ff7f7ac447c85c46c923da53389221a0054c11c1e3ca31d59\(dq,
      \(dqamount_msat\(dq: 400000,
      \(dqamount_sent_msat\(dq: 400000,
      \(dqcreated_at\(dq: 1722303718,
      \(dqcompleted_at\(dq: 1722303719,
      \(dqstatus\(dq: \(dqcomplete\(dq,
      \(dqpayment_preimage\(dq: \(dqaf67b48518e78e157db404d13cb42987c31e034634203d10b224302b05fc6c90\(dq,
      \(dqbolt11\(dq: \(dqlnbcrt1pn2s3xxsp5xvccgadvepzypat5v8u8tstwdvn9ez4908h7ntl4s0ggx76ug4cqpp50qwurth9swdlzphjvjc2qm8sws8jcu0u28y4vt5s7nhr3js0c3vsdqcdserzgryv4ekxunfwp6xjmmwxqyjw5qcqp9rzjqdwjkyvjm7apxnssu4qgwhfkd67ghs6n6k48v6uqczgt88p6tky96qqqduqqqqgqqqqqqqqpqqqqqzsqqc9qxpqysgqw4qfxj30wqn2m2qmcfz2gs6ttszdhkc0kjqk0mgg59tj2cy90wcke4tjzmzakrkvcgqgf3367j47q5g2ruuw67cxaqxm2t4m42yecsqp92jzs7\(dq
    }
  ]
}
.EE
.PP
