.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-TXDISCARD" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-txdiscard -- Abandon a transaction from txprepare, release inputs
.SH
SYNOPSIS
.LP
\fBtxdiscard\fR \fItxid\fR 
.SH
DESCRIPTION
.LP
The \fBtxdiscard\fR RPC command releases inputs which were reserved for use of the \fItxid\fR from lightning-txprepare(7).
.IP "\(bu" 2
\fBtxid\fR (txid): The transaction id, inputs should be unreseverd from.
.SH
RETURN VALUE
.LP
On success, an object is returned, containing:
.IP "\(bu" 2
\fBunsigned_tx\fR (hex): The unsigned transaction.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBtxid\fR (txid): The transaction id of \fIunsigned_tx\fR.
.LP
If there is no matching \fItxid\fR, an error is reported. Note that this may happen due to incorrect usage, such as \fBtxdiscard\fR or \fBtxsend\fR already being called for \fItxid\fR.
.SH
ERRORS
.LP
The following error codes may occur:
.IP "\(bu" 2
-1: An unknown \fItxid\fR.
.SH
AUTHOR
.LP
Rusty Russell <\fIrusty@rustcorp.com.au\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-txprepare(7), lightning-txsend(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli txdiscard \(dqcafef1e6936d05584c8406e9ec5e9631b03513fe8b2a0444c5824e1a1f3d7c67\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:txdiscard#1\(dq,
  \(dqmethod\(dq: \(dqtxdiscard\(dq,
  \(dqparams\(dq: [
    \(dqcafef1e6936d05584c8406e9ec5e9631b03513fe8b2a0444c5824e1a1f3d7c67\(dq
  ]
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqunsigned_tx\(dq: \(dq0200000001974bc23173b7bca9b060dac12abd1bb158e8ed69a3e74d4f6af5919b15f5772c0100000000fdffffff020000000100000000220020a056363be8c7dbb511098cc50fbca24843e6ed6de03f816465f1998a9a82a09d4183980000000000225120f1393467c717cd50de2760167d4311141a8f750c89f54fd2c900601a7da8434c95000000\(dq,
  \(dqtxid\(dq: \(dqcafef1e6936d05584c8406e9ec5e9631b03513fe8b2a0444c5824e1a1f3d7c67\(dq
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli txdiscard -k \(dqtxid\(dq=\(dq91a189eb69a436e49735ae1e8619fd96a342a4e5c63fa2baa7e9f69ecdc7434c\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:txdiscard#2\(dq,
  \(dqmethod\(dq: \(dqtxdiscard\(dq,
  \(dqparams\(dq: {
    \(dqtxid\(dq: \(dq91a189eb69a436e49735ae1e8619fd96a342a4e5c63fa2baa7e9f69ecdc7434c\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqunsigned_tx\(dq: \(dq02000000010cbdd42439292d7a59620493020f2a204488bfa4d640eedb84af5d3bd6479aea0000000000fdffffff0240420f00000000002200200fefd5034808bec0c94b857b7a3ddeeece7cae1b2101b2f23f1c114b14073f31b7a1f000000000002251205c54c6ff7b25c08e66a91d4256a5ca2c374ab1faf56377e8d65466cf997614ce97000000\(dq,
  \(dqtxid\(dq: \(dq91a189eb69a436e49735ae1e8619fd96a342a4e5c63fa2baa7e9f69ecdc7434c\(dq
}
.EE
.PP
