.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-BKPR-CHANNELSAPY" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-bkpr-channelsapy -- Command to list stats on channel earnings
.SH
SYNOPSIS
.LP
\fBbkpr-channelsapy\fR [\fIstart_time\fR] [\fIend_time\fR] 
.SH
DESCRIPTION
.LP
The \fBbkpr-channelsapy\fR RPC command lists stats on routing income, leasing income, and various calculated APYs for channel routed funds.
.IP "\(bu" 2
\fBstart_time\fR (u64, optional): UNIX timestamp (in seconds) to filter events after the provided timestamp. The default is zero.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBend_time\fR (u64, optional): UNIX timestamp (in seconds) to filter events up to and at the provided timestamp. The default is max-int.
.SH
RETURN VALUE
.LP
On success, an object containing \fBchannels_apy\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBaccount\fR (string): The account name. If the account is a channel, the channel_id. The 'net' entry is the rollup of all channel accounts.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBrouted_out_msat\fR (msat): Sats routed (outbound).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBrouted_in_msat\fR (msat): Sats routed (inbound).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlease_fee_paid_msat\fR (msat): Sats paid for leasing inbound (liquidity ads).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlease_fee_earned_msat\fR (msat): Sats earned for leasing outbound (liquidity ads).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpushed_out_msat\fR (msat): Sats pushed to peer at open.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBpushed_in_msat\fR (msat): Sats pushed in from peer at open.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBour_start_balance_msat\fR (msat): Starting balance in channel at funding. Note that if our start balance is zero, any _initial field will be omitted (can't divide by zero).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBchannel_start_balance_msat\fR (msat): Total starting balance at funding.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfees_out_msat\fR (msat): Fees earned on routed outbound.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fButilization_out\fR (string): Sats routed outbound / total start balance.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fButilization_in\fR (string): Sats routed inbound / total start balance.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_out\fR (string): Fees earned on outbound routed payments / total start balance for the length of time this channel has been open amortized to a year (APY).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_in\fR (string): Fees earned on inbound routed payments / total start balance for the length of time this channel has been open amortized to a year (APY).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_total\fR (string): Total fees earned on routed payments / total start balance for the length of time this channel has been open amortized to a year (APY).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBfees_in_msat\fR (msat, optional): Fees earned on routed inbound.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fButilization_out_initial\fR (string, optional): Sats routed outbound / our start balance.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fButilization_in_initial\fR (string, optional): Sats routed inbound / our start balance.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_out_initial\fR (string, optional): Fees earned on outbound routed payments / our start balance for the length of time this channel has been open amortized to a year (APY).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_in_initial\fR (string, optional): Fees earned on inbound routed payments / our start balance for the length of time this channel has been open amortized to a year (APY).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_total_initial\fR (string, optional): Total fees earned on routed payments / our start balance for the length of time this channel has been open amortized to a year (APY).
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBapy_lease\fR (string, optional): Lease fees earned over total amount leased for the lease term, amortized to a year (APY). Only appears if channel was leased out by us.
.SH
AUTHOR
.LP
Lisa Neigut <\fIniftynei@gmail.com\fR> is mainly responsible.
.SH
SEE ALSO
.LP
lightning-bkpr-listincome(7), lightning-bkpr-listfunds(7), lightning-bkpr-listaccountevents(7), lightning-bkpr-dumpincomecsv(7), lightning-listpeers(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli bkpr-channelsapy
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:bkpr-channelsapy#1\(dq,
  \(dqmethod\(dq: \(dqbkpr-channelsapy\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqchannels_apy\(dq: [
    {
      \(dqaccount\(dq: \(dq252d1b0a1e57895e84137f28cf19ab2c35847e284c112fefdecc7afeaa5c1de7\(dq,
      \(dqrouted_out_msat\(dq: 1000000,
      \(dqrouted_in_msat\(dq: 510081208,
      \(dqlease_fee_paid_msat\(dq: 0,
      \(dqlease_fee_earned_msat\(dq: 0,
      \(dqpushed_out_msat\(dq: 0,
      \(dqpushed_in_msat\(dq: 0,
      \(dqour_start_balance_msat\(dq: 0,
      \(dqchannel_start_balance_msat\(dq: 1000000000,
      \(dqfees_out_msat\(dq: 0,
      \(dqfees_in_msat\(dq: 106,
      \(dqutilization_out\(dq: \(dq0.1000%\(dq,
      \(dqutilization_in\(dq: \(dq51.0081%\(dq,
      \(dqutilization_in_initial\(dq: \(dq51.0081%\(dq,
      \(dqapy_out\(dq: \(dq0.0000%\(dq,
      \(dqapy_in\(dq: \(dq0.0252%\(dq,
      \(dqapy_in_initial\(dq: \(dq0.0252%\(dq,
      \(dqapy_total\(dq: \(dq0.0252%\(dq
    },
    {
      \(dqaccount\(dq: \(dqa397dd9b3e44afcb67f3f3ce1d649b74a8ade63e35505985e4cc1828634f69a2\(dq,
      \(dqrouted_out_msat\(dq: 510181102,
      \(dqrouted_in_msat\(dq: 0,
      \(dqlease_fee_paid_msat\(dq: 0,
      \(dqlease_fee_earned_msat\(dq: 0,
      \(dqpushed_out_msat\(dq: 0,
      \(dqpushed_in_msat\(dq: 0,
      \(dqour_start_balance_msat\(dq: 1000000000,
      \(dqchannel_start_balance_msat\(dq: 1000000000,
      \(dqfees_out_msat\(dq: 106,
      \(dqfees_in_msat\(dq: 0,
      \(dqutilization_out\(dq: \(dq51.0181%\(dq,
      \(dqutilization_out_initial\(dq: \(dq51.0181%\(dq,
      \(dqutilization_in\(dq: \(dq0.0000%\(dq,
      \(dqapy_out\(dq: \(dq0.0505%\(dq,
      \(dqapy_out_initial\(dq: \(dq0.0505%\(dq,
      \(dqapy_in\(dq: \(dq0.0000%\(dq,
      \(dqapy_total\(dq: \(dq0.0505%\(dq,
      \(dqapy_total_initial\(dq: \(dq0.0505%\(dq
    },
    {
      \(dqaccount\(dq: \(dqf8fc83a432cbfb2fffe222cc06727fdd977b5dd10ebd6707158e799e6f522d9f\(dq,
      \(dqrouted_out_msat\(dq: 500000000,
      \(dqrouted_in_msat\(dq: 0,
      \(dqlease_fee_paid_msat\(dq: 0,
      \(dqlease_fee_earned_msat\(dq: 0,
      \(dqpushed_out_msat\(dq: 0,
      \(dqpushed_in_msat\(dq: 0,
      \(dqour_start_balance_msat\(dq: 1000000000,
      \(dqchannel_start_balance_msat\(dq: 1000000000,
      \(dqfees_out_msat\(dq: 0,
      \(dqfees_in_msat\(dq: 0,
      \(dqutilization_out\(dq: \(dq50.0000%\(dq,
      \(dqutilization_out_initial\(dq: \(dq50.0000%\(dq,
      \(dqutilization_in\(dq: \(dq0.0000%\(dq,
      \(dqapy_out\(dq: \(dq0.0000%\(dq,
      \(dqapy_out_initial\(dq: \(dq0.0000%\(dq,
      \(dqapy_in\(dq: \(dq0.0000%\(dq,
      \(dqapy_total\(dq: \(dq0.0000%\(dq,
      \(dqapy_total_initial\(dq: \(dq0.0000%\(dq
    },
    {
      \(dqaccount\(dq: \(dqnet\(dq,
      \(dqrouted_out_msat\(dq: 1011181102,
      \(dqrouted_in_msat\(dq: 510081208,
      \(dqlease_fee_paid_msat\(dq: 0,
      \(dqlease_fee_earned_msat\(dq: 0,
      \(dqpushed_out_msat\(dq: 0,
      \(dqpushed_in_msat\(dq: 0,
      \(dqour_start_balance_msat\(dq: 2000000000,
      \(dqchannel_start_balance_msat\(dq: 3000000000,
      \(dqfees_out_msat\(dq: 106,
      \(dqfees_in_msat\(dq: 106,
      \(dqutilization_out\(dq: \(dq33.7060%\(dq,
      \(dqutilization_out_initial\(dq: \(dq50.5591%\(dq,
      \(dqutilization_in\(dq: \(dq17.0027%\(dq,
      \(dqutilization_in_initial\(dq: \(dq51.0081%\(dq,
      \(dqapy_out\(dq: \(dq0.0084%\(dq,
      \(dqapy_out_initial\(dq: \(dq0.0126%\(dq,
      \(dqapy_in\(dq: \(dq0.0084%\(dq,
      \(dqapy_in_initial\(dq: \(dq0.0252%\(dq,
      \(dqapy_total\(dq: \(dq0.0168%\(dq,
      \(dqapy_total_initial\(dq: \(dq0.0168%\(dq
    }
  ]
}
.EE
.PP
