.\" -*- mode: troff; coding: utf-8 -*-
.TH "LIGHTNING-LISTPEERS" "7" "" "Core Lightning pre-v24.08" ""
.SH
NAME
.LP
lightning-listpeers -- Command returning data on connected lightning nodes
.SH
SYNOPSIS
.LP
\fBlistpeers\fR [\fIid\fR] [\fIlevel\fR] 
.SH
DESCRIPTION
.LP
The \fBlistpeers\fR RPC command returns data on nodes that are connected or are not connected but have open channels with this node.
.PP
Once a connection to another lightning node has been established, using the \fBconnect\fR command, data on the node can be returned using \fBlistpeers\fR and the \fIid\fR that was used with the \fBconnect\fR command.
.PP
If no \fIid\fR is supplied, then data on all lightning nodes that are connected, or not connected but have open channels with this node, are returned.
.PP
If a channel is open with a node and the connection has been lost, then the node will still appear in the output of the command and the value of the \fIconnected\fR attribute of the node will be \(dqfalse\(dq.
.PP
The channel will remain open for a set blocktime, after which if the connection has not been re-established, the channel will close and the node will no longer appear in the command output.
.IP "\(bu" 2
\fBid\fR (pubkey, optional): If supplied, limits the result to just the peer with the given ID, if it exists.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlevel\fR (string, optional) (one of \(dqio\(dq, \(dqtrace\(dq, \(dqdebug\(dq, \(dqinfo\(dq, \(dqunusual\(dq): Supplying level will show log entries related to that peer at the given log level.
.SH
RETURN VALUE
.LP
On success, an object containing \fBpeers\fR is returned. It is an array of objects, where each object contains:
.IP "\(bu" 2
\fBid\fR (pubkey): The unique id of the peer.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBconnected\fR (boolean): Value showing the connection status.
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBnum_channels\fR (u32): The number of channels the peer has with this node. \fI(added v23.02)\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 2
\fBlog\fR (array of objects, optional): If \fIlevel\fR is specified, logs for this peer.:
.RS
.IP "\(bu" 2
\fBtype\fR (string) (one of \(dqSKIPPED\(dq, \(dqBROKEN\(dq, \(dqUNUSUAL\(dq, \(dqINFO\(dq, \(dqDEBUG\(dq, \(dqTRACE\(dq, \(dqIO_IN\(dq, \(dqIO_OUT\(dq)
.RE
.IP
If \fBtype\fR is \(dqSKIPPED\(dq:
- \fBnum_skipped\fR (u32): Number of deleted/omitted entries.
.IP
If \fBtype\fR is \(dqBROKEN\(dq, \(dqUNUSUAL\(dq, \(dqINFO\(dq, \(dqDEBUG\(dq or \(dqTRACE\(dq:
- \fBtime\fR (string): UNIX timestamp with 9 decimal places.
- \fBsource\fR (string): The particular logbook this was found in.
- \fBlog\fR (string): The actual log message.
- \fBnode_id\fR (pubkey): The peer this is associated with.
.IP
If \fBtype\fR is \(dqIO_IN\(dq or \(dqIO_OUT\(dq:
- \fBtime\fR (string): UNIX timestamp with 9 decimal places.
- \fBsource\fR (string): The particular logbook this was found in.
- \fBlog\fR (string): The actual log message.
- \fBnode_id\fR (pubkey): The peer this is associated with.
- \fBdata\fR (hex): The IO which occurred.
.LP
If \fBconnected\fR is \fItrue\fR:
- \fBnetaddr\fR (array of strings): A single entry array.:
- (string, optional): Address, e.g. 1.2.3.4:1234.
- \fBfeatures\fR (hex): Bitmap of BOLT #9 features from peer's INIT message.
- \fBremote_addr\fR (string, optional): The public IPv4/6 address the peer sees us from, e.g. 1.2.3.4:1234.
.SH
ERRORS
.LP
On error the returned object will contain \fCcode\fR and \fCmessage\fR properties, with \fCcode\fR being one of the following:
.IP "\(bu" 2
-32602: If the given parameters are wrong.
.SH
AUTHOR
.LP
Michael Hawkins <\fImichael.hawkins@protonmail.com\fR>.
.SH
SEE ALSO
.LP
lightning-connect(7), lightning-fundchannel_start(7), lightning-setchannel(7)
.SH
RESOURCES
.LP
Main web site: \fIhttps://github.com/ElementsProject/lightning\fR
Lightning RFC site (BOLT #9):
\fIhttps://github.com/lightning/bolts/blob/master/09-features.md\fR
.SH
EXAMPLES
.LP
\fBExample 1\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listpeers -k \(dqid\(dq=\(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listpeers#1\(dq,
  \(dqmethod\(dq: \(dqlistpeers\(dq,
  \(dqparams\(dq: {
    \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq
  }
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpeers\(dq: [
    {
      \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqconnected\(dq: true,
      \(dqnum_channels\(dq: 2,
      \(dqnetaddr\(dq: [
        \(dq127.0.0.1:34785\(dq
      ],
      \(dqfeatures\(dq: \(dq08a0802a8a59a1\(dq
    }
  ]
}
.EE
.PP
\fBExample 2\fR: 
.PP
Request:
.LP
.EX
$ lightning-cli listpeers
.EE
.LP
.EX
{
  \(dqid\(dq: \(dqexample:listpeers#2\(dq,
  \(dqmethod\(dq: \(dqlistpeers\(dq,
  \(dqparams\(dq: {}
}
.EE
.PP
Response:
.LP
.EX
{
  \(dqpeers\(dq: [
    {
      \(dqid\(dq: \(dq035d2b1192dfba134e10e540875d366ebc8bc353d5aa766b80c090b39c3a5d885d\(dq,
      \(dqconnected\(dq: true,
      \(dqnum_channels\(dq: 2,
      \(dqnetaddr\(dq: [
        \(dq127.0.0.1:34785\(dq
      ],
      \(dqfeatures\(dq: \(dq08a0802a8a59a1\(dq
    },
    {
      \(dqid\(dq: \(dq032cf15d1ad9c4a08d26eab1918f732d8ef8fdc6abb9640bf3db174372c491304e\(dq,
      \(dqconnected\(dq: true,
      \(dqnum_channels\(dq: 1,
      \(dqnetaddr\(dq: [
        \(dq127.0.0.1:38251\(dq
      ],
      \(dqfeatures\(dq: \(dq08a0802a8a59a1\(dq
    },
    {
      \(dqid\(dq: \(dq0266e4598d1d3c415f572a8488830b60f7e744ed9235eb0b1ba93283b315c03518\(dq,
      \(dqconnected\(dq: true,
      \(dqnum_channels\(dq: 1,
      \(dqnetaddr\(dq: [
        \(dq127.0.0.1:47032\(dq
      ],
      \(dqfeatures\(dq: \(dq08a0802a8a59a1\(dq
    }
  ]
}
.EE
.PP
